### ISSUE TITLE
Centralised Error Handling

### ISSUE THREAD

**Issue by DSAghicha** [krishnaacharyaa/wanderlust#1]
Adding a centralized error handler will prevent the application for crashing and becoming unavailable.

**Comment by krishnaacharyaa** [comment]
Hi @DSAghicha 
Welcome you onboard :)

Can you kindly elaborate more on the issue, meaning how is the error handled presently and why adding centralised error handling will be beneficial.
So that I can assign this issue to you 
And in the PR you can explain your approach and how it will enhance the existing application's error handling.

**Comment by DSAghicha** [comment]
1. Having a centralized error handler, catches any unknown errors and based on criticality, we can also implement adding a mailer which will mail any critical server side error.
2. Instead of handling error in every single endpoint, it will be in a central method. This will help in effective refactoring of code and implement DRY principles.
3. It can also, intimate the new contributors about any config issue/mistake that might make.
   Ex. I haven't create the .env file causing my application to crash.
        ![image](https://github.com/krishnaacharyaa/wanderlust/assets/53931676/80bf970a-be57-4e67-acd1-25b33748af08)
       Here, error handler would inform the member to properly mention the URI in the env file.

**Comment by krishnaacharyaa** [comment]
That seems a really best practice :)
Kindly implement this in all the places we make the api calls, db connection and any potential error prone areas
I'm assigning this issue to you.

**Comment by krishnaacharyaa** [comment]
Hi @DSAghicha, can you kindly let us know the ETA to resolve this issue, new potential contributors are aiming to solve this otherwise, 
Thank you :)
