### ISSUE TITLE
[ENHANCEMENT] Refactoring of all the md: to sm:

### ISSUE THREAD

**Issue by Deblin798** [krishnaacharyaa/wanderlust#102]
### Description

We can aim for default classes (mobile), sm (tablet), lg (desktop if explicitly required), and lets refactor all the other classes if it were using md.

### Current Behavior

The current codebase uses the md: prefix for classes to define styling and behavior, presumably targeted at medium-sized devices. The specific styling associated with these classes may be tailored for devices with a medium screen size, such as tablets or devices in a certain resolution range.

### Proposed Enhancement

The proposed enhancement involves refactoring the existing codebase to improve class naming conventions and create a more consistent structure. The main changes include:

Replacing all instances of md: with sm: to better reflect the intended target, focusing on small to medium-sized devices.

### Use Case

The sm: classes, replacing the existing md: classes, would be employed for tablet-sized devices, providing a tailored layout and styling for this category.

**Comment by Chelseasingla1** [comment]
> ### Description
> We can aim for default classes (mobile), sm (tablet), lg (desktop if explicitly required), and lets refactor all the other classes if it were using md.
> 
> ### Current Behavior
> The current codebase uses the md: prefix for classes to define styling and behavior, presumably targeted at medium-sized devices. The specific styling associated with these classes may be tailored for devices with a medium screen size, such as tablets or devices in a certain resolution range.
> 
> ### Proposed Enhancement
> The proposed enhancement involves refactoring the existing codebase to improve class naming conventions and create a more consistent structure. The main changes include:
> 
> Replacing all instances of md: with sm: to better reflect the intended target, focusing on small to medium-sized devices.
> 
> ### Use Case
> The sm: classes, replacing the existing md: classes, would be employed for tablet-sized devices, providing a tailored layout and styling for this category.
> 
> ### Blockers
> _No response_
> 
> ### Additional Information/ Attachments
> _No response_

@krishnaacharyaa Hi sir i texted you from discord can you please assign me this issue under GSSoC'24? I would like to work on it.

**Comment by krishnaacharyaa** [comment]
Sure @Chelseasingla1 Please let me know the ETA and kindly keep in mind the contributing guidelines

**Comment by Chelseasingla1** [comment]
> Sure @Chelseasingla1 Please let me know the ETA and kindly keep in mind the contributing guidelines

@krishnaacharyaa Okay sir, I will try to submit it by this afternoon only.
