### ISSUE TITLE
app is not dockerize

### ISSUE THREAD

**Issue by imkuldeepahlawat** [krishnaacharyaa/wanderlust#103]
### Description

Docker enables more efficient use of system resources

### Current Behavior

app current is depend on  node dependency

### Proposed Enhancement

i can dockerize the app so anyone can use directly , without any dependency except docker

### Use Case

it will solve the issue , developement setup

**Comment by imkuldeepahlawat** [comment]
should i contribute on this issue

**Comment by krishnaacharyaa** [comment]
Hi @imkuldeepahlawat , thank you for creating this issue and really appreciate the interest in solving this issue,
But we have the docker containers with docker in place if you go to the dockerization branch in our rep.
Kindly feel free to pick any other open issue, would love to have your support in the project 😊

p.s: Sorry for the late reply, missed it
