### ISSUE TITLE
[BUG] No Loading screen when posts are filtered based on the category 

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you click on the category, lets say `Nature`, then the title gets updated to "Posts related to "Nature"", but the posts related to nature are loading after some delay, which causes confusion

### Expected Behavior

When you click on the category, lets say `Nature`, then the title gets updated to "Posts related to "Nature"", then there should be loading shimmer effect (reuse the exisiting one which is loaded for the intial post rendering), After the filtered posts (Nature posts) is loaded, it should be shown in the UI, This will avoid the confusion and the user will know that there is data fetch happening.

### Reproduction URL

https://wanderlust-beta.vercel.app/

### Reproduction steps

```bash
1. Click on Nature
2. Watch the behaviour in the featured posts section
```

### Browsers

Chrome

### OS

Windows

**Comment by PrakharSinha-09** [comment]
hey @krishnaacharyaa , can I take up this issue ?

**Comment by krishnaacharyaa** [comment]
Sure @PrakharSinha-09, can you kindly let me know in brief how you are gonna solve the issue and time estimate to solve the problem, so that I am confident to assign 😊

**Comment by PrakharSinha-09** [comment]
will try to get it done by tomorrow itself, the approach is pretty easy since the time post related to certain categories has not came up, we can render skeleton in the meantime

**Comment by krishnaacharyaa** [comment]
Cool, use the exisiting skeletons... 👍🏻
Assigning it to you 🙂
