### ISSUE TITLE
[BUG] All posts card is not inline with the skeleton (shimmer card)

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1534" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/459f87ee-572b-4255-80ec-2530e1ee33f1">

<img width="1539" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/c3b67235-ab91-4c9e-a8b9-4bac5aa5d55c">

### Expected Behavior

1. Title and description should be full, with some padding at right
2. Reduce the gap between the categories shimmer in the last row
3. Handle for the mobile screen aswell

### Reproduction URL

https://wanderlust-beta.vercel.app/

### Reproduction steps

```bash
1. Navigate to the URL 
2. When posts are initial loaded, we see that the actual content and the card skeleton is not same
```

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by SahilSuman1011** [comment]
Hii Krishna , hope you are doing good .  I want to contribute to the frontend of this project . can you please assign this to me .

**Comment by krishnaacharyaa** [comment]
What is the approach @SahilSuman1011 you are gonna follow and ETA

**Comment by SahilSuman1011** [comment]
i am gonna work on the ui part to make it look more bright and catchy .

**Comment by krishnaacharyaa** [comment]
Okay pro tip @SahilSuman1011 
If you wanna grow in this open source community... Show that you are actually into the project and actually want to create an impact.... Soo see your comments it is very generally thrown and may be to 10s of project, there is no attention to detail...
So the one who wants to assign you , will never assign you because you don't know what you are doing and you just want some points or somehow got the PR merged...

It won't happen...
Stick to a project understand it ... Try to contribute thoroughly.
You'll be benefited with good amount of points and the PA and mentor also will have a positive feedback...

This no one might tell you, felt like sharing it...
Who knows if you follow this ... You may reach somewhere in the leaderboard 

All the best 🙂👍🏻

**Comment by Chelseasingla1** [comment]
> ### Expected Behavior
> 1. Title and description should be full, with some padding at right
> 2. Reduce the gap between the categories shimmer in the last row
> 3. Handle for the mobile screen aswell
> 
> ### Reproduction URL

@krishnaacharyaa Can you please assign me this issue under GSSoC'24 i would like to work on it.

**Comment by Chelseasingla1** [comment]
> > ### Expected Behavior
> > 
> > 1. Title and description should be full, with some padding at right
> > 2. Reduce the gap between the categories shimmer in the last row
> > 3. Handle for the mobile screen aswell
> > 
> > ### Reproduction URL
> 
> @krishnaacharyaa Can you please assign me this issue under GSSoC'24 i would like to work on it.

Thankyou sir for assigning!!

**Comment by Chelseasingla1** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> <img alt="image" width="1534" src="https://private-user-images.githubusercontent.com/116620586/316258580-459f87ee-572b-4255-80ec-2530e1ee33f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk5NTUsIm5iZiI6MTcxNTU5OTY1NSwicGF0aCI6Ii8xMTY2MjA1ODYvMzE2MjU4NTgwLTQ1OWY4N2VlLTU3MmItNDI1NS04MGVjLTI1MzBlMWVlMzNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTI3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTM5MzI3ZmE5YzEyYmJkOGZlM2ZhYzA1ODgyOWU2ODg0ZWFmYThjMDM2ZDJlMWE0M2ZjZjI1NWUyMjI0MzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u2JbuxaZuZX8oNkR9_szeVU-F9Lj4PQwdsrEP5YPF4I"> <img alt="image" width="1539" src="https://private-user-images.githubusercontent.com/116620586/316258562-c3b67235-ab91-4c9e-a8b9-4bac5aa5d55c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk5NTUsIm5iZiI6MTcxNTU5OTY1NSwicGF0aCI6Ii8xMTY2MjA1ODYvMzE2MjU4NTYyLWMzYjY3MjM1LWFiOTEtNGM5ZS1hOGI5LTRiYWM1YWE1ZDU1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTI3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjUxNDhlMGZmM2QzNDgxNDNjMGE1YjNmZmQzOTJhZTY1OTJlYzMwYzc2ZjIyNDFmYjE4ZjA3OTRiMDVhZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qKpmhwz1F1OAkyo-TS7lcqL_8T0qB46z7nQq_wiVKWI">
> ### Expected Behavior
> 1. Title and description should be full, with some padding at right
> 2. Reduce the gap between the categories shimmer in the last row
> 3. Handle for the mobile screen aswell
> 
> ### Reproduction URL
> https://wanderlust-beta.vercel.app/
> 
> ### Reproduction steps
> ```shell
> 1. Navigate to the URL 
> 2. When posts are initial loaded, we see that the actual content and the card skeleton is not same
> ```
> 
> ### Logs
> _No response_
> 
> ### Browsers
> _No response_
> 
> ### OS
> _No response_

@krishnaacharyaa There is one issue with description if we want full description it is possible but because of one i am facing issues should i decrease its content?
![Screenshot 2024-05-13 165713](https://github.com/krishnaacharyaa/wanderlust/assets/129886894/155092ce-75ff-4b5b-8d41-e1bd0af98d52)

Otherwise it is okay!!

**Comment by Chelseasingla1** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Current Behavior
> > <img alt="image" width="1534" src="https://private-user-images.githubusercontent.com/116620586/316258580-459f87ee-572b-4255-80ec-2530e1ee33f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk5NTUsIm5iZiI6MTcxNTU5OTY1NSwicGF0aCI6Ii8xMTY2MjA1ODYvMzE2MjU4NTgwLTQ1OWY4N2VlLTU3MmItNDI1NS04MGVjLTI1MzBlMWVlMzNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTI3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTM5MzI3ZmE5YzEyYmJkOGZlM2ZhYzA1ODgyOWU2ODg0ZWFmYThjMDM2ZDJlMWE0M2ZjZjI1NWUyMjI0MzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u2JbuxaZuZX8oNkR9_szeVU-F9Lj4PQwdsrEP5YPF4I"> <img alt="image" width="1539" src="https://private-user-images.githubusercontent.com/116620586/316258562-c3b67235-ab91-4c9e-a8b9-4bac5aa5d55c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk5NTUsIm5iZiI6MTcxNTU5OTY1NSwicGF0aCI6Ii8xMTY2MjA1ODYvMzE2MjU4NTYyLWMzYjY3MjM1LWFiOTEtNGM5ZS1hOGI5LTRiYWM1YWE1ZDU1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTI3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjUxNDhlMGZmM2QzNDgxNDNjMGE1YjNmZmQzOTJhZTY1OTJlYzMwYzc2ZjIyNDFmYjE4ZjA3OTRiMDVhZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qKpmhwz1F1OAkyo-TS7lcqL_8T0qB46z7nQq_wiVKWI">
> > ### Expected Behavior
> > 
> > 1. Title and description should be full, with some padding at right
> > 2. Reduce the gap between the categories shimmer in the last row
> > 3. Handle for the mobile screen aswell
> > 
> > ### Reproduction URL
> > https://wanderlust-beta.vercel.app/
> > ### Reproduction steps
> > ```shell
> > 1. Navigate to the URL 
> > 2. When posts are initial loaded, we see that the actual content and the card skeleton is not same
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Logs
> > _No response_
> > ### Browsers
> > _No response_
> > ### OS
> > _No response_
> 
> @krishnaacharyaa There is one issue with description if we want full description it is possible but because of one i am facing issues should i decrease its content? ![Screenshot 2024-05-13 165713](https://private-user-images.githubusercontent.com/129886894/330036967-155092ce-75ff-4b5b-8d41-e1bd0af98d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDAwNTgsIm5iZiI6MTcxNTU5OTc1OCwicGF0aCI6Ii8xMjk4ODY4OTQvMzMwMDM2OTY3LTE1NTA5MmNlLTc1ZmYtNGI1Yi04ZDQxLWUxYmQwYWY5OGQ1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmVlOWQwMjYwMTEyMWFjN2NlYzYzNGEwZTlmNmNmZGUwMTJmMWMwYTFhMDc4NmE0Y2FlMTk2MmEzM2I3OWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._jRZ1VUtVuss_B_nHUkNBZG3WjBKViEsmaodf-aZyq4)
> 
> Otherwise it is okay!!

Or if not then it would be like this showing a little less description:
![image](https://github.com/krishnaacharyaa/wanderlust/assets/129886894/22534b4b-e74b-4d90-9a00-6c2a7c2a6107)

**Comment by krishnaacharyaa** [comment]
> @krishnaacharyaa There is one issue with description if we want full description it is possible but because of one i am facing issues should i decrease its content?

But wait @Chelseasingla1 what are you working on? Why is this description soo long? Don't touch anything here....
You just have to mimick the height and width of the shimmers (skeleton here)

**Comment by krishnaacharyaa** [comment]
https://github.com/krishnaacharyaa/wanderlust/pull/143/files

your code changes, will look like this in its relevant file, may be all-blog-skeleton file
@Chelseasingla1 that's it

I didn't understand how this description became big and why it is the concern, in production we don't have such description

**Comment by Chelseasingla1** [comment]
> https://github.com/krishnaacharyaa/wanderlust/pull/143/files
> 
> your code changes, will look like this in its relevant file, may be all-blog-skeleton file @Chelseasingla1 that's it
> 
> I didn't understand how this description became big and why it is the concern, in production we don't have such description

@krishnaacharyaa Ohkay i thought you want full description i got it now thankyou i will make changes accordingly now.
