### ISSUE TITLE
[BUG] Featured posts card is not inline with the skeleton card (shimmer card)

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1039" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/688c0faa-3f5b-42f6-b3c3-3b46f14632b5">
<img width="1054" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/2ca831fb-0e60-47b6-91a0-093375dbd907">

### Expected Behavior

1. Right  Column 2nd row should be removed.
2. Description's height should be increased to match the actual description height
3. Handle for the mobile screen aswell

### Reproduction URL

https://wanderlust-beta.vercel.app/

### Reproduction steps

```bash
1. Navigate to the URL 
2. When posts are initial loaded, we see that the actual content and the card skeleton is not same in the featured posts section
```

**Comment by SohamRoy-01** [comment]
can I work on this issue @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
Yeah @SohamRoy-01 Please
The solution should be simple you just have to mimic the actual post with skeleton post, make sure all the expected behaviour is met and please follow the contributing guidelines.
Assigning to you
