### ISSUE TITLE
Write script to run both frontend and backend at same time

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#11]
Presently we have to first enter backend and then do `npm start` and then open frontend in another terminal and do `npm run dev`.
It would be nice to have script in the `package.json` in the app level which runs both, 
ex: `npm start` should run both backend and frontend

**Comment by hemant14050** [comment]
Hello @krishnaacharyaa ,
- Should I use any third party package (ex. https://www.npmjs.com/package/concurrently) ?
- If so then, please assign it me.
- If not then, let me any other approach.

**Comment by krishnaacharyaa** [comment]
Sure @hemant14050 
Yes you need to use concurrently package

Go through https://blog.logrocket.com/running-react-express-concurrently/ and kindly make sure if we need any more changes in our project w.r.t scripts which enhances the maintainability of the project and adds value.
