### ISSUE TITLE
[BUG] Latest posts card is not inline with the skeleton card (shimmer card) 

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="519" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/d9017b22-e707-4ae2-b099-eb713eae8d5a">
<img width="526" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/661e6bca-bdf4-42a3-acee-fc03f5c00386">

### Expected Behavior

1. 3rd row to be removed
2. The Author and Date row should be further wider
3. Handle for the mobile screen aswell

### Reproduction URL

https://wanderlust-beta.vercel.app/

### Reproduction steps

```bash
1. Navigate to the URL 
2. When posts are initial loaded, we see that the actual content and the card skeleton is not same
```

**Comment by SankalpHaritash21** [comment]
Hi @krishnaacharyaa  can I take this issue

**Comment by krishnaacharyaa** [comment]
Sure @SankalpHaritash21

**Comment by kami-codes** [comment]
@krishnaacharyaa is this completed?

**Comment by krishnaacharyaa** [comment]
No @kami-codes, you can take this up, Didn't hear from @SankalpHaritash21 for quite a few days, may be he is occupied.

**Comment by SankalpHaritash21** [comment]
@krishnaacharyaa  u can assign this task to @kami-codes  as i am working on admin login will soon complete it and will back to you as soon as possible.

**Comment by kami-codes** [comment]
@SankalpHaritash21 @krishnaacharyaa 
okay I will start doing it soon.

**Comment by SankalpHaritash21** [comment]
Hi @krishnaacharyaa I would not be able to complete by Sunday as I am out of station.

**Comment by devsharmagit** [comment]
@krishnaacharyaa 
I have raised a PR regarding this bug.
I also noticed some more issues. How can I raise them?

**Comment by krishnaacharyaa** [comment]
> I also noticed some more issues. How can I raise them?

@devsharmagit  You can just raise an issue and use the bug template and fill in the details

**Comment by adititapariya** [comment]
@krishnaacharyaa I'd like to work on the issue for GSSoC'24. Could you please assign me this task?

**Comment by krishnaacharyaa** [comment]
Okay @adititapariya feel free to work on it, hoping you'll take a day max to complete, kindly follow the community guidelines

**Comment by krishnaacharyaa** [comment]
@adititapariya quick tip the solution is already there, the pr is not merged because he didn't follow the commit guidelines, please make sure you do that, rest you have it in hand
