### ISSUE TITLE
[BUG] We have to scroll to find the footer even if there is space for the footer in the description, add blog page in both desktop and mobile

### ISSUE THREAD

**Issue by Mohitsen11** [krishnaacharyaa/wanderlust#121]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

User has to scroll down the page to find/locate the footer even if there is space available.

### Expected Behavior

Footer should dynamically adjust its position based on the content height of each page (AddBlog, DetailsPage). When the content height is less than the viewport height, the footer should be visible at the bottom of the viewport without requiring scrolling. Conversely, when the content height exceeds the viewport height, the footer should remain at the bottom of the content area, allowing users to scroll down to find it. This ensures consistent visibility and accessibility of the footer across all pages of the application.

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/'
2. Click on 'Create post/ Any post to read details'
3. See issue
```

### Screenshots

Current behavior 
![Screenshot (86)](https://github.com/krishnaacharyaa/wanderlust/assets/114509045/14c8c52f-440b-4617-943d-74fde46ce895)

![Screenshot (83)](https://github.com/krishnaacharyaa/wanderlust/assets/114509045/1d6b2469-acca-4d05-9d54-757b3fc7cf3f)

Expected behavior
![Screenshot (85)](https://github.com/krishnaacharyaa/wanderlust/assets/114509045/4aabaa4f-77c3-40d8-964d-1991b16d6506)

![Screenshot (84)](https://github.com/krishnaacharyaa/wanderlust/assets/114509045/13e3ddd9-cadf-4ab5-b8d1-4f8ee61c72cf)

**Comment by kami-codes** [comment]
Hey I can take this issue.
It's a small UI issue I am sure i can solve it

**Comment by Mohitsen11** [comment]
> Hey I can take this issue. It's a small UI issue I am sure i can solve it

@kami-codes Go ahead, if you are willing to fix it.

**Comment by kami-codes** [comment]
@Mohitsen11 I raise a PR about that
