### ISSUE TITLE
Make the HomePage responsive for all the devices

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#13]
Presently the font looks too big and it doesn't have proper styling which is not suitable for the mobile devices
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/78a4d29c-6b25-4461-85a6-f5dd05c689ae)

We have to make it responsive for devices 
1. Greater than desktop
2. Desktop devices
3. Tablet devices
4. mobile devices

**Comment by CODEX108** [comment]
Hello Krishna,
can you assign this issue to me?

**Comment by krishnaacharyaa** [comment]
Sure @CODEX108 , please let me know you how you are gonna solve this issue, post that will assign to you :)

**Comment by krishnaacharyaa** [comment]
@CODEX108 , please find the figma design file in the readme and plan accordingly, and make sure to use reusable component

**Comment by MhaskeAditya42** [comment]
Hey Krishna ! 
As as you asked this is how I am going to proceed with this issue 
So basically I will add the breakpoints in css code of that page according to the screen size of mobile , tablets and desktops and change the font size , container size etc.
Positioning of buttons and text also. 
So can you please assign it to me

**Comment by krishnaacharyaa** [comment]
Hi @MhaskeAditya42 by " I will add the breakpoints in css code" do you mean adding breakpoint prefixes ? If you didn't already know we are using tailwind-css in this project, so ideal case would be adding the required classes for sm and lg device classes, which will cover mobile, tablet and desktop screen sizes. Please clarify on the same

**Comment by MhaskeAditya42** [comment]
@krishnaacharyaa. Sorry I did not have idea that we are using tailwind css in this project so We can directly use classes like sm for mobile screens , md for tablet screens and lg for desktop screen . We can set padding, margins etc according to this screens

**Comment by krishnaacharyaa** [comment]
@MhaskeAditya42 No Problem,
So instead of `sm` for mobile screens
Lets do it this way, as tailwind supports mobile first design, default it will support mobile screens
For tablet lets aim `sm`
and for desktop lets aim `lg`

So we will be dealing with mobile devices (default) , tablet (>= sm && < lg) and desktop ( >=lg)

**Comment by krishnaacharyaa** [comment]
I'll assign this to you, please make sure you follow the PR guidelines before raising PR, 
Which includes

- [ ] Make sure the PR title is of format **`tag: Issue Title`**
   - tag should be one of `fix`,`feat`, `docs`, `chore`, `refactor`
   - Ex: `feat: Added responsive design for the home page`
- [ ] Ensure the code follows our coding standards and guidelines
   - Ex:  naming conventions should be of form `file-name.ts` not `fileName.ts`
- [ ] Ensure that you have staged only the required commits and raised the PR and not included all the files which would be otherwise required for local setup
- [ ] Check if the PR is rebased to the latest main/development branch.
- [ ] Make sure there are no unnecessary files or debugging artifacts in the PR.

**Comment by krishnaacharyaa** [comment]
And follow the figma design for responsive design , available in the `readme.md`

**Comment by krishnaacharyaa** [comment]
@MhaskeAditya42 May i kindly know the progress, till where have we reached ...

**Comment by MhaskeAditya42** [comment]
<img width="1440" alt="Screenshot 2023-11-05 at 23 40 23" src="https://github.com/krishnaacharyaa/wanderlust/assets/94377039/27faba03-4f4f-45d4-a5d3-ae84033422ea">
I am getting this error database is connected successfully but data is not being loaded although I have completed the upper part of the page which is carousel.

**Comment by krishnaacharyaa** [comment]
@MhaskeAditya42 , it shouldn't ideally happen because we are using cors policy in the express js backend server, It may be some browser specific issue that you are facing 

<img width="1676" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/81dfa42b-5444-4acb-8f7c-c3a963b83c26">
In the latest master we have everything clean and running ...

**Comment by MhaskeAditya42** [comment]
![Uploading Screenshot 2023-11-06 at 12.18.43.png…]()
@krishnaacharyaa I tried using chrome also but I am getting same error.

**Comment by MhaskeAditya42** [comment]
![Uploading Screenshot 2023-11-06 at 12.18.43.png…]()
@krishnaacharyaa I tried using chrome also but I am getting same error.

**Comment by krishnaacharyaa** [comment]
Can you kindly try setting up again, from scratch. Because we aren't able to reproduce the issue

**Comment by Shashmit** [comment]
Hey would love to change the font values in devices that are larger than mobile size as tailwind is first mobile then other. As well as work on building custom components so that they can be used later on in different section of codes.

**Comment by krishnaacharyaa** [comment]
> @MhaskeAditya42 No Problem, So instead of `sm` for mobile screens Lets do it this way, as tailwind supports mobile first design, default it will support mobile screens For tablet lets aim `sm` and for desktop lets aim `lg`
> 
> So we will be dealing with mobile devices (default) , tablet (>= sm && < lg) and desktop ( >=lg)

Thank you for the interest, we can take one thing at a time, first we can focus on making it mobile responsive and then we can refactor it to use the components. Kindly refer the above to get a brief idea of the plan, and follow the commit guidelines (CONTRIBUTING GUIDELINES ) :)

**Comment by Bhargav-varma-0** [comment]
> @MhaskeAditya42 , it shouldn't ideally happen because we are using cors policy in the express js backend server, It may be some browser specific issue that you are facing
> 
> <img alt="image" width="1676" src="https://private-user-images.githubusercontent.com/116620586/280548003-81dfa42b-5444-4acb-8f7c-c3a963b83c26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDcwODMsIm5iZiI6MTcwMjEwNjc4MywicGF0aCI6Ii8xMTY2MjA1ODYvMjgwNTQ4MDAzLTgxZGZhNDJiLTU0NDQtNGFjYi04ZjdjLWMzYTk2M2I4M2MyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwNzI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2ZkODg0OGZkMGJhYzFlYTI0ZGYwMjhjYTI4MmZhMDYyODI0ZGQxYjczMjRhMWMwYjdkZDU0ZWVjMDI4NDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K1KIj07nvG8LU0yJ63lxKYM7bINcllcy4B9FqWvBuiU"> In the latest master we have everything clean and running ...

use Uinq key for the list items your Your generating Like if you created a separate Componet and Your calling it in an iteration 
You should use key= {uniqKey} as prop

**Comment by geetanjalichawla** [comment]
@krishnaacharyaa can you assign me this

**Comment by krishnaacharyaa** [comment]
Can you give me rough time estimate @geetanjalichawla

**Comment by geetanjalichawla** [comment]
2 days i would say @geetanjalichawla
