### ISSUE TITLE
Make the Details Page responsive

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#14]
Presently the styles are disoriented and the arrow is shadowed by the title and the tags are invisible and also fix the text font sizes
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/245024a6-bca7-4e89-b613-f698fe00295f)

We have to make it responsive for devices 
1. Greater than desktop
2. Desktop devices
3. Tablet devices
4. mobile devices

**Comment by SankalpHaritash21** [comment]
I will try to make this detail page responsive using sm, md and lg.
will fix font size according to the desig

**Comment by krishnaacharyaa** [comment]
Sure @SankalpHaritash21
I will assign this to you, please make sure to follow the PR guidelines aswell
