### ISSUE TITLE
Make the add page responsive 

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#15]
Presently the categories are disoriented and the font size is too big and horizontal padding is too big and we might have to span the button full width for best practice in the mobile device
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/21c74898-06e0-4168-9d4d-19fda0976b83)

We have to make it responsive for devices 
1. Greater than desktop
2. Desktop devices
3. Tablet devices
4. mobile devices

**Comment by SankalpHaritash21** [comment]
I can make it responsive by adding break point it for multiple devices

**Comment by krishnaacharyaa** [comment]
Can you please elaborate by adding break point what exactly do you mean ?

**Comment by SankalpHaritash21** [comment]
Full Screen View
![full](https://github.com/krishnaacharyaa/wanderlust/assets/110713125/3324cb8f-7dc3-4b2f-920b-cd5b8b103f52)


Mobile View
![mobile](https://github.com/krishnaacharyaa/wanderlust/assets/110713125/61f1f7fa-fd48-49e2-a977-ff5265fd0206)

**Comment by krishnaacharyaa** [comment]
You are posting the images which i posted in the issue description, please add the equivalent description, by adding breakpoints what you mean , create new css file ? adding tailwind breakpoints ? or how is it that you are planning to take care of responsiveness

**Comment by SankalpHaritash21** [comment]
screens: {
      xs: "420px",
      sm: "640px", // Small screens
      md: "768px", // Medium screens
      lg: "1024px", // Large screens
    },

These are the break point which I am going to use for making website responsive

**Comment by krishnaacharyaa** [comment]
Sure you can consider only sm and lg for now i.e
1. All the classes which are not specified with the breakpoint prefixs are mobile
2. class with sm will support tablet 
3. class with lg will support desktop and above  

So you dont have to explicitly add these in the tailwind.config.ts, instead we can work with only `sm` and `lg` and the default values of these would do :)
