### ISSUE TITLE
[BUG] Theme changes to light mode on page refresh in add blogs page

### ISSUE THREAD

**Issue by AnirudhMemani** [krishnaacharyaa/wanderlust#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user has a dark theme selected and refreshes the page, the theme changes to light mode.

https://github.com/krishnaacharyaa/wanderlust/assets/46074384/1f95ad4c-189b-4d3d-865d-c8fa3443f778

### Expected Behavior

It should not switch to light theme on page refresh.

### Reproduction steps

```bash
+ Select dark mode
+ Refresh the page
```

### Browsers

Chrome

### OS

Windows

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!
