### ISSUE TITLE
[BUG] Categories Sidebar UI issue While Theme changes, Alignment changes

### ISSUE THREAD

**Issue by Deepanshushar** [krishnaacharyaa/wanderlust#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### BUG- on left sidebar inside <sup> Categories Container </sup> there is a box showing, while change on Theme ###

- On Repetitive switch of Theme There can be seen under the "Categories Box", there is a box over "Tags".

### Reproduction steps

```bash
1. Go to 'Home Page'
2. Switch to 'Theme Dark to Light Reputative'
3. See a box over the Tags 
4. also affecting design of website
```

### Screenshots

![LightMode](https://github.com/krishnaacharyaa/wanderlust/assets/107925102/2e0dba99-639a-4e45-a112-d558fa30c64f)
![DarkMode](https://github.com/krishnaacharyaa/wanderlust/assets/107925102/8ae2ca1c-aa00-4c37-a7c3-646a6c63c385)

### Browsers

Chrome

### OS

Windows

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by amit429** [comment]
@krishnaacharyaa Hey can you please assign me this task under GSSOC'24 tag

**Comment by krishnaacharyaa** [comment]
@amit429 please let us know ETA

**Comment by krishnaacharyaa** [comment]
@thefarhanahmad sorry missed it, kindly pick up some other issue, join our discord

**Comment by amit429** [comment]
> @amit429 please let us know ETA

2 days

**Comment by amit429** [comment]
@krishnaacharyaa I have identified and fixed the box over the tags bug in the UI during dark mode for better User Experience while toggle
