### ISSUE TITLE
[BUG] I can access /admin-blog page, even if I have not logged in 

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If i access directly via url `https://wanderlust-beta.vercel.app/add-blog` without logging in, I can easily view the page. 

### Expected Behavior

Ideally only if the user is authenticated he should be let to view the page, else we should show page of "Oops sorry you are not authorized for this page"

### Reproduction steps

```bash
1. Don't login 
2. Go to https://wanderlust-beta.vercel.app/add-blog
3. You'll be able to view the page
```

**Comment by Ameerjafar** [comment]
can i work on this sir please assign me @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
Hi @Ameerjafar Can you kindly let us know your approach and ETA? And kindly refer the above PR, it says this issue has dependency with #172 issue. So ideally we need to solve it and then get back to this

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by bikashsahh** [comment]
kindly assign this task to me.I can help with this bug

**Comment by krishnaacharyaa** [comment]
@bikashsahh @thefarhanahmad  [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share)

**Comment by krishnaacharyaa** [comment]
Closed as resolved
