### ISSUE TITLE
[ENHANCEMENT] Add husky in the project  

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#177]
### Description

It would nice to have pre-commit hooks which will do 3 things
1. Run the prettier and format the code
2. Add a regex for the commit message as mentioned in the contributing guidelines
3. Run the test cases to ensure nothing is breaking
4. Check eslint and make sure nothing is breaking ( Meaning in production once deployed we get error the variable is not used, those needs to be handled here)

### Current Behavior

Currently we can add anything directly, we need to restrict this and catch the errors early

### Proposed Enhancement

Add husky to increase the security and consistency

### Use Case

Ensures only the quality code is let to commit 

### Additional Information/ Attachments

<img width="923" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/8fa5975a-6552-4f1d-8bf1-ce598052a544">
Example such type of errors needs to handled before commiting.  would be a great edition.

Can be used as one of the ref: https://leandroaps.medium.com/building-a-modern-react-app-with-vite-vitest-typescript-eslint-prettier-and-husky-abc7a9876e9d

**Comment by Ameerjafar** [comment]
@krishnaacharyaa  can i work on it sir.

**Comment by krishnaacharyaa** [comment]
@Ameerjafar Sure. This is need of the hour actually, it might be little challenging...
Are you up for it ? It would involve little research....

If you are up for it, kindly take it up... Very much appreciated if you can do it within a day or 2 as we are now going for GSSoC

**Comment by Ameerjafar** [comment]
@krishnaacharyaa let me work on it.

**Comment by krishnaacharyaa** [comment]
Sure @Ameerjafar assigning it to you

**Comment by krishnaacharyaa** [comment]
Hi @Ameerjafar, May I know where are we on this? If we could do this a bit fast paced that would be great actually...
As we have mates joining us from GSSoC

**Comment by Ameerjafar** [comment]
almost completed sir can i continue sir @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
Yes please @Ameerjafar , can you kindly raise PR by EOD if possible, That would be really greatful!

**Comment by Ameerjafar** [comment]
can i add two .husky folder in the both frontend and backend or only one for common sir @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
@Ameerjafar can you see if it can be done from one place? If not we'll have it in both the places...
I guess we have to have it in both the places

**Comment by krishnaacharyaa** [comment]
@Ameerjafar , can you please join the discord and message me, have some things to share regarding the issue.....

**Comment by Ameerjafar** [comment]
sir let me join in discord sir @krishnaacharyaa.
