### ISSUE TITLE
[FEATURE] Adding admin functionality to the frontend

### ISSUE THREAD

**Issue by devsharmagit** [krishnaacharyaa/wanderlust#178]
### Description

1 Admin routes shouldn't be accessible when the URL is directly entered.
2 owner of the post should be able to edit and delete his own post
3 admin should be able to see the edit and delete post option like the 2nd point like post owner. At the same time has his dedicated window using 3rd point.

### Use Case

This feature will complete the admin functionality to the frontend.

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by bikashsahh** [comment]
Hi there! , will like to resolve this issue.

**Comment by razerbotog** [comment]
i would love to resolve this issue. I am a GSSOC 24 contributor.

### **Propose Solution**

- [ ] Will make  a reusable Layout to protect certain routes.
- [ ] Need to store user is **Admin** or not in a global state by using native useContext hook or using library like redux-toolkit.

**The question is**
Are we getting admin value in user data  or not ? 
If not i would also love to  fix this issue along with the above one.
