### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [krishnaacharyaa/wanderlust#188]
### Description

A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

### Current Behavior

Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. 

### Proposed Enhancement

I would like to add the code of conduct file.

### Use Case

Please assign this issue to me under GSSOC 24

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me

**Comment by krishnaacharyaa** [comment]
HI @suhanipaliwal what is ETA and how do you want to proceed with this issue? I have some inputs, if you can make it quick I'll be happy to assign you

**Comment by krishnaacharyaa** [comment]
Hi @suhanipaliwal  Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by aasthakourav20** [comment]
Hey @krishnaacharyaa We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md
Please assign this task to  me

**Comment by aasthakourav20** [comment]
Really sorry sir , I didn't mean to spam . I think, I just misunderstood the things as I am  just a new Contributor to GSSOC . Please assign me the issue , I would be more concerned next time .
Once again really sorry sir !!

**Comment by officeneerajsaini** [comment]
@krishnaacharyaa  , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me? if @aasthakourav20  is not working on issue .

**Comment by krishnaacharyaa** [comment]
@officeneerajsaini interested in contributing in the github-actions part? Join the discord server we'll discuss.

And @aasthakourav20 how much time is it taking? You have file content you just have to add the file, do copy paste and raise the PR, hope it is a easy task

**Comment by aasthakourav20** [comment]
Really sorry , I was  facing some problems in pulling request, even after making changes , it's showing no changes .
But I would work upon it  , will resolve this surely

**Comment by aasthakourav20** [comment]
Hey @krishnaacharyaa , I did the necessary changes, please check out

**Comment by krishnaacharyaa** [comment]
First off I am not able to see the PR.
And who's code of conduct is this? I don't want this content, I have it here https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3 Just copy paste, 

And kindly follow contributing guidelines, else your PR will not get merged.
Take your time read the guidelines see, how merged PRs have their commit message and raise a PR

**Comment by officeneerajsaini** [comment]
> Really sorry , I was  facing some problems in pulling request, even after making changes , it's showing no changes .
> But I would work upon it  , will resolve this surely 

You need any help ? I'm here

**Comment by aasthakourav20** [comment]
Thankyou so much guys for your cooperation.

**Comment by officeneerajsaini** [comment]
> Thankyou so much guys for your cooperation.

Ping me on discord . Search on discord group my username name is "officeneerajsaini" .

**Comment by officeneerajsaini** [comment]
@krishnaacharyaa  please add gssoc or level tags  this issue.

**Comment by krishnaacharyaa** [comment]
> @krishnaacharyaa please add gssoc or level tags this issue.

First let someone raise a valid PR, while valid PR is getting merged I'll add it even if it is missed here, shouldn't be much  of a problem
