### ISSUE TITLE
[ENHANCEMENT] Implementing routed page for each section i.e hot post , new posts (latest post ) and all post can be displayed in home page. #UX Consideration

### ISSUE THREAD

**Issue by Adeesh-bode** [krishnaacharyaa/wanderlust#198]
### Description

This enhancement involves the implementation of routed pages for distinct sections of a website, specifically for 'Hot Posts', 'New Posts' (Latest Posts), and 'All Posts'. These sections will be accessible from the homepage and are designed to improve the site's organizational structure and user navigation. By creating dedicated routes for each post category, users can seamlessly navigate to different content streams, enhancing the site’s usability and overall user experience.

### Current Behavior

Clustured Section, New user would Struggle to access  information ( would skip small heading )

### Proposed Enhancement

Consider a popular blogging platform looking to enhance user engagement and content discoverability. By introducing routed pages for 'Hot Posts', 'New Posts', and 'All Posts', the platform can cater to varied user preferences and needs efficiently. For instance, a visitor interested in trending topics can click on the 'Hot Posts' link from the homepage and be directed to a page that aggregates posts receiving the most interaction. Similarly, someone looking for the latest content can navigate to the 'New Posts' section.

### Use Case

Consider a popular blogging platform looking to enhance user engagement and content discoverability. By introducing routed pages for 'Hot Posts', 'New Posts', and 'All Posts', the platform can cater to varied user preferences and needs efficiently. For instance, a visitor interested in trending topics can click on the 'Hot Posts' link from the homepage and be directed to a page that aggregates posts receiving the most interaction. Similarly, someone looking for the latest content can navigate to the 'New Posts' section.

**Comment by krishnaacharyaa** [comment]
@Adeesh-bode Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by krishnaacharyaa** [comment]
Closing as it violates [code of conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3)
