### ISSUE TITLE
Running app on multiple processes

### ISSUE THREAD

**Issue by DSAghicha** [krishnaacharyaa/wanderlust#2]
This will help in load handling of the application.

**Comment by krishnaacharyaa** [comment]
Hi @DSAghicha, Please elaborate what are the drawbacks of the existing application and how this will enhance and overcome the drawbacks

**Comment by DSAghicha** [comment]
By default, nodejs application runs on a single core. In large applications this adds load on a single core to process request and upon crashing renders entire application unavailable. This approach will make our nodejs application to run on all cores as instances.
Ex. The ```http://localhost:5000/``` endpoint of the application which simply returns a string when accessed by 10000 users, takes an average time of  18.9ms
![image](https://github.com/krishnaacharyaa/wanderlust/assets/53931676/f96aca16-cded-4cb9-8005-de47ba15d383)
After clustering and running app on all available cores, the average time is reduced to 16.9ms
![image](https://github.com/krishnaacharyaa/wanderlust/assets/53931676/42b9691e-ca5c-489e-9619-de6fee1b2365)
This significantly improves performance of complex endpoints.

**Comment by krishnaacharyaa** [comment]
Yeah this is interesting, We can go ahead with this 👍🏻

**Comment by shmbajaj** [comment]
@DSAghicha Interesting, I suggest not to implement rather document it and increase the complexity and user base and later in the future we can implement it.

I haven't observed any lag and long wait times.

@krishnaacharyaa what's your take on this?

**Comment by krishnaacharyaa** [comment]
>@DSAghicha Interesting, I suggest not to implement rather document it and increase the complexity and user base and later in the future we can implement it.

Yeah @shmbajaj, I share the same opinion, lets park it for now

**Comment by DSAghicha** [comment]
> >@DSAghicha Interesting, I suggest not to implement rather document it and increase the complexity and user base and later in the future we can implement it.
> 
> Yeah @shmbajaj, I share the same opinion, lets park it for now

Ok, I will update the document and raise a PR by this weekend.
