### ISSUE TITLE
[ENHANCEMENT] Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [krishnaacharyaa/wanderlust#202]
### Description

Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started.

### Current Behavior

The current README is not visually appealing.

### Proposed Enhancement

I propose to make it more visually appealing by adding badges for tech stack, visiter count, issue count, fork count and other items.

Below are some samples:
![image](https://github.com/krishnaacharyaa/wanderlust/assets/120160355/1744cec7-e9d0-4027-b5b5-a15e18f7ff18)
![image](https://github.com/krishnaacharyaa/wanderlust/assets/120160355/10029112-d03d-46e2-8680-9128cfeba168)

### Use Case

It improves the readability for users. It also makes the readme visually appealing.

**Comment by jinx-vi-0** [comment]
hey @krishnaacharyaa , please assign this issue to me.

**Comment by krishnaacharyaa** [comment]
> The current README is not visually appealing.

It's a bold statement have to say!!

Can you come up with interactive icons for discord and figma? The latest 2024 looking ones ofcourse not the examples you have provided, looks 2010's tbh. See my github profile for a better readme format

**Comment by jinx-vi-0** [comment]
ya sure. I had the new discord one on my profile too.

**Comment by krishnaacharyaa** [comment]
@jinx-vi-0 please come up with an image or approach and what are things you wanna add, once done we can carry it from there

**Comment by krishnaacharyaa** [comment]
Closing as it violates [code of conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3)
