### ISSUE TITLE
[BUG] 5000 Port number is reserved by default on Macos

### ISSUE THREAD

**Issue by lakshz** [krishnaacharyaa/wanderlust#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the default port number of the backend service is 5000. 
Setting up the backend by following `README.md` throws `EADDRINUSE` on some latest version of macos, since 5000 port is reserved by default on it.
Ref: https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c
 

### Expected Behavior

Easy solution is to switch to some other port, that doesn't interfere with any of OS related processes. Let's do `8080` since it's a common port for local development in Node.js

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### OS

Mac

**Comment by lakshz** [comment]
I can fix this.

**Comment by krishnaacharyaa** [comment]
No offence, I have a mac and it works just fine, please work on some interesting issue, even if you do this you'll not get satisfaction. Aim for a bigger fish and hunt it down, you'll get good points in GSSoC if that's the end goal.

Kindly follow [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3
)

**Comment by lakshz** [comment]
No sweat. Every issue I create can't be for my learning curve, this was to make project setup easier and help beginners. GSSoC points is not the end goal, currently.

**Comment by krishnaacharyaa** [comment]
Okay cool, I'll trust you and apologize for the reply, if helping people is your aim, let's kindly connect in the Discord... And we have lots to discuss...

Pardon me to misunderstand
