### ISSUE TITLE
[FEATURE] : Scroll to Top Button for Improved User Experience

### ISSUE THREAD

**Issue by antriksh-9** [krishnaacharyaa/wanderlust#206]
### Description

On [website](https://wanderlust-beta.vercel.app/) a back-to-top button isn't present which is a common website feature.

I propose adding a "Scroll to Top" button that becomes visible as the user scrolls down the website page.
Tapping this button would smoothly scroll the user back to the top, providing a convenient and efficient way to navigate lengthy content.

### Use Case

Tapping the "Scroll-to-top" button would smoothly scroll the user back to the top, providing a convenient and efficient way to navigate lengthy content.

**Comment by krishnaacharyaa** [comment]
Please follow [code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3)
