### ISSUE TITLE
[ENHANCEMENT] The navbar should appear at top while scrolling as well .

### ISSUE THREAD

**Issue by Apoorva-Rajput** [krishnaacharyaa/wanderlust#209]
### Description

The navbar at home page should be moving while scrolling the page and fixed to top and the logo of website should redirect to the homepage for better user experience.
@krishnaacharyaa kindly look into the issue . I want to work on this please assign it to me .
And suggest any changes if required .

### Current Behavior

Currently it is fixed at top which is not user friendly .

### Proposed Enhancement

I would like to add the sticky navbar feature using HTML, CSS, Javascript. I am open to suggestions as well.

### Use Case

This enhancement will benefit user's experience on the website , as while they scroll down on homepage and then proceeds to login etc. they do not need to scroll to top . And navbar should be accessible throughout the website surfing .

**Comment by Apoorva-Rajput** [comment]
@krishnaacharyaa kindly assign the issue to me under GSSoC'24 label .

**Comment by krishnaacharyaa** [comment]
Kindly find the code-of-conduct of the project [Code-of-conduct] @Apoorva-Rajput 
  Closing as issue already exists
