### ISSUE TITLE
[FEATURE]  Additional of Tour Package section 

### ISSUE THREAD

**Issue by Nitin8426** [krishnaacharyaa/wanderlust#217]
### Description

A well-designed tour package feature can be a powerful tool to attract travelers and streamline the booking process on your travel website. 

### Use Case

Easy-to-use filters: Allow users to filter tours by destination, duration, activity type (hiking, sightseeing, etc.), budget, travel style (luxury, adventure, etc.), and even theme (e.g., family vacations, cultural immersion).
Clear search results: Display tours with high-quality photos, concise descriptions, and key details like price, departure dates, and inclusions (flights, accommodation, meals, activities)

### Proposed Solution

Tour Package Content:

Detailed itineraries: Provide a day-by-day breakdown of the tour, including transportation, accommodation, activities, and free time.
Inclusions and exclusions: Clearly outline what's included in the base price and what travelers will need to pay extra for (optional activities, meals, travel insurance, etc.).
High-quality visuals: Use professional photos and videos to showcase destinations, accommodations, and activities.

Booking System:

Seamless booking process: Allow users to easily book tours directly on your website with a secure payment gateway.
Flexibility: Consider offering options for customization, where travelers can choose their flights or upgrade their accommodation.
Clear confirmation: Provide a confirmation email with all the essential details of the booked tour package.

### Additional Information

Customer reviews and testimonials: Showcase positive feedback from past travelers to build trust and credibility.
Live chat support: Offer real-time assistance to users who have questions about specific tour packages.
Travel add-ons: Allow users to add additional services to their package, such as airport transfers, travel insurance, or local tours.

### Attachments

Screenshot 
![Screenshot_20240513-183900](https://github.com/krishnaacharyaa/wanderlust/assets/164453064/3b6d0035-6010-4681-92d0-79c7ebd9d97c)

Please Assign me this issue under GSSoC 2024.

**Comment by krishnaacharyaa** [comment]
Closing as it violates [code of conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3)
