### ISSUE TITLE
[ENHANCEMENT] Different Cards under all posts are of different height ,.

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [krishnaacharyaa/wanderlust#220]
### Description

Some Cards in All posts section are showing to be of different length .
![Screenshot 2024-05-13 195455](https://github.com/krishnaacharyaa/wanderlust/assets/118350936/b7139701-c94c-4093-a772-dba619568bc8)

### Current Behavior

Showing cards of different length .

### Proposed Enhancement

Cards will be of same length .

### Use Case

Scroll to the about us section and compare the height of different cards. 

### Additional Information/ Attachments

![Screenshot 2024-05-13 195455](https://github.com/krishnaacharyaa/wanderlust/assets/118350936/2fd75bc8-dd6c-44b3-b315-a8c361afac32)

**Comment by Ayushmaanagarwal1211** [comment]
Yes i wanna work on that Under GSSOC'24

**Comment by krishnaacharyaa** [comment]
Sure go ahead @Ayushmaanagarwal1211

**Comment by Alen-Scaria1516** [comment]
Hi @krishnaacharyaa can you assign me this issue? I will make the PR as proposed in the Discord channel.

**Comment by krishnaacharyaa** [comment]
Sure @Alen-Scaria1516

**Comment by RituGupta23** [comment]
hi @krishnaacharyaa can you assign this issue to me?

**Comment by Alen-Scaria1516** [comment]
@krishnaacharyaa have raised a pull request. Thank you for letting me work on this issue.
