### ISSUE TITLE
[FEATURE]  Adding search bar at home page 

### ISSUE THREAD

**Issue by Nitin8426** [krishnaacharyaa/wanderlust#221]
### Description

A well-designed search bar is crucial for any travel website, as it allows users to quickly and easily find the travel options that suit their needs. Here's what makes a great search bar feature for travel websites:

### Use Case

Clear and concise presentation: Search results should be easy to understand, showcasing destinations, dates, prices, and brief descriptions.
Sorting and filtering: Allow users to sort results by price, rating, or other criteria.

### Proposed Solution

Destination: This is a core element, allowing users to enter a specific city, region, or even landmark they'd like to visit.
Dates: Users should be able to choose flexible travel dates, including options for weekend getaways or trips within a specific month or season. User-friendly calendar interfaces are a plus.
Travel style (optional): Some sites allow filtering by travel style, such as adventure, luxury, family-friendly, or romantic getaways.
Budget (optional): An option to search within a desired price range can be helpful. 

### Additional Information

Past searches: Some sites offer the option to see past searches, which can be helpful for revisiting previous considerations.

### Attachments

![Screenshot_20240513-202103](https://github.com/krishnaacharyaa/wanderlust/assets/164453064/640b4140-a8f4-4690-b6ab-5651dffbd9c4)

Assign me this issue under GSSoC 2024. I will take care of background and refrence of website.

**Comment by krishnaacharyaa** [comment]
Closing as it violates [code of conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3)
If there was an option to block you , would have definitely done it :)

**Comment by Nitin8426** [comment]
Sorry, for the inconvenience caused
