### ISSUE TITLE
[FEATURE] Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [krishnaacharyaa/wanderlust#227]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.

### Use Case

It will allow only genuine users only.
It will help to avoid any bot.

### Proposed Solution

I will add a feature so that no one could create an account using **temporary or disposable email**.

### Additional Information

Assign me this work under GSSoC24, I will implement it.

**Comment by krishnaacharyaa** [comment]
@pankaj-bind kindly let us know the approach and ETA

**Comment by pankaj-bind** [comment]
I will use an API which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email".
It's a part of frontend, it does not affects backend.
It is not like email verification using OTP.
e.g. [pankajbind30@gmail.com](mailto:pankajbind30@gmail.com) (this is a genuine email) and [mixat67435@losvtn.com](mailto:mixat67435@losvtn.com) (This is a temporary or disposable email). My solution identifies this.
I have tried this, and this feature is very unique.

**Comment by krishnaacharyaa** [comment]
Okay go for it! pankaj-bind.
Just make sure you follow the guidelines
