### ISSUE TITLE
[FEATURE] Github Action to validate the PR

### ISSUE THREAD

**Issue by sanmarg** [krishnaacharyaa/wanderlust#230]
### Description

Task: As soon as the PR is raised, GitHub Bot should check the PR content and see and match it with regex basically our format and check the commits for the community guidelines and prompt saying you have not followed the code guidelines  and then close the PR if it doesn't follow

### Use Case

Helps to automate the task

### Proposed Solution

You need to write a github action on PR raised trigger and may be run a script

### Acceptance criteria

1. PR should have title of  "tag-#<number>: title" or "tag:title" format 
2. The commit should have the very similar "tag-#<number>: title" or "tag-: title" format, you might have to iterate through all the commits
3. The commit regex to be run as soon as commit is pushed in the PR even, see if it requires another workflow bot!?
4. It should have all of these four titles
<img width="838" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/102b92ee-066b-4189-9802-bc0d04c11b3e">
5. And the Issue(s) address section shouldn't have the default description like this
<img width="446" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/d8d514fa-c672-4425-ac8c-9252a44b8d61">

**Comment by krishnaacharyaa** [comment]
<img width="917" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/9167be86-b48c-4587-ae60-15223a9fa790">

How can you have please assign to me in the description???!!

**Comment by krishnaacharyaa** [comment]
Hi @Mayur-666, I have updated the acceptance criteria, please look into it, make sure you actualy test it in your other project and confirm things and then raise PR. If it is too much feel free to split into diff PRs so you can get max points.

cc: @sanmarg

**Comment by krishnaacharyaa** [comment]
Hi @Mayur-666 
Let's take this ....
And start with this as discussed...
Let's not mix anything for this ..
And it is not greeting message..
As mentioned in the closed PR comment section

**Comment by Mayur-666** [comment]
well it is working, some checks are still required, 
want to confirm ->  is it what you were looking ??

![Screenshot (542)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/32dda759-a381-4980-be61-65d1535885ed)

![Screenshot (543)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/cb8057bf-9256-4f77-9ab5-8b6fdaa11acc)


The github bot auto closed pr cause pr title did not followed a specific pattern, it checks for body too.

**Comment by Mayur-666** [comment]
@krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
> The github bot auto closed pr cause pr title did not followed a specific pattern, it checks for body too.

First can we have for the title only in the first try and let it not directly auto close tell them why it is closed, i don't see any error message in the first one. And the error message should be very very understandable.

Like
Hey Thanks for your PR, But unfortunately it doesn't quality checks!!
Wait!!! Have you gone through our contribution guidelines? I guess you didn't care xD

I'll not let you raise the PR until you follow the regex!! -> "<tag>-<issue-number>: Title of the PR"
Didn't get it? I guess so take a look at this example. It should be something like "fix-#124: Added responsivenes to the Home page screen"

Give it a try, I may reopen it for you;)

Keep it mean, keep it funny and like the guy in the other github i shared you , it needs to reopen once he corrects it....
Can we just focus on only this PR title part? close with mean, funny error message and then auto open if it is correct!

@Mayur-666 I know I am crazy, But I guess you can relate tooo know ;)

**Comment by krishnaacharyaa** [comment]
@Mayur-666 acknowledgement? Or very scary feature request?

**Comment by Mayur-666** [comment]
@krishnaacharyaa  I'll try sir, but not able to work on it for next 2 days. Going off town with my brother for his CUET exam.
