### ISSUE TITLE
[FEATURE] <Add like feature>

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [krishnaacharyaa/wanderlust#246]
### Description

allow users to like others posts.

### Use Case

Likes serve as immediate feedback for bloggers, indicating that their content is appreciated and resonating with the audience. This positive reinforcement can motivate bloggers to continue creating content, fostering a vibrant and active community.

### Proposed Solution

I have already familiar with the blogging app backend. You can check it [here](https://github.com/DharshiBalasubramaniyam/Blogie-backend/blob/main/controllers/likeController.js). Here i have created separate controller and route for like.

I can also have abilities to create the frontend as well. 

I am very much excited to contribute like stuff to this project. Please assign this issue to me under GSSOC'24

**Comment by DharshiBalasubramaniyam** [comment]
Hi @krishnaacharyaa,  please assign this issue to me.

**Comment by krishnaacharyaa** [comment]
Violates the code of conduct
