### ISSUE TITLE
Add Scroll-to-Top Button To The Website and Style Vertical Scrollbar 

### ISSUE THREAD

**Issue by MastanSayyad** [krishnaacharyaa/wanderlust#248]
### Description

Hi @krishnaacharyaa ,
A Scroll-To-Top Button can provide a convenient way for users to quickly return to the top of the page. Additionally, I believe styling the vertical scrollbar would improve the visual appeal and user experience.

### Use Case

**The benefits of adding scroll-to-top button and styling vertical scrollbar:**
- Improved User Experience.
- Enhanced Accessibility.
- A vertical scroll bar and scroll-to-top button demonstrate attention to detail.
- These features contribute to a positive first impression of the website.

### Proposed Solution

- A **Scroll-To-Top Button** for users to quickly return to the top of the page by creating a new react component.
- Customize the style of vertical scrollbar's color, width, and shape to enhance the scrollbar's appearance and **match the website's design theme.**

### Additional Information

As I have previously worked on a similar tech stack, I'd like to take on the task, 
**Could you please assign this project to me Under GSSoC'24 so that I can start working on it?**

**Comment by krishnaacharyaa** [comment]
Not required for now
