### ISSUE TITLE
[FEATURE] adding a chatbot

### ISSUE THREAD

**Issue by nagamukesh** [krishnaacharyaa/wanderlust#252]
### Description

i can add a chatbot to explain user our website and give some suggestions and answer his/her queries

### Use Case

Lets say he/she doubts the some climatic conditions etc of a place which may not be covered in the data given
chatbot can help
as we cannot provide the entire information of a place(some events currently happening in that place), and some info needs to be edited/changed continuously(fees to visit,prices,some policies etc) 
chat bot can help as it searches our website and the internet to give accurate results
please assign this issue to me under gssoc 2024
I can add a chatbot

**Comment by Srishtiii19** [comment]
hello, I can add chatbot in your project.  Here is a screenshot of chatbot that i have added in my previous project: 

![Screenshot (378)](https://github.com/krishnaacharyaa/wanderlust/assets/121797105/4264d3f0-98e0-4ae7-9826-db11ab484796)
![Screenshot (377)](https://github.com/krishnaacharyaa/wanderlust/assets/121797105/eeb705ed-dff7-4cde-a511-c964a335d667)

Please assign me to contribute in this project under GSSoC'24.
