### ISSUE TITLE
Hide and visible in password to improve UI

### ISSUE THREAD

**Issue by GOURAVSINGH19** [krishnaacharyaa/wanderlust#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is good to add seen  and unseen feature in sing in page . It give a choice to user to check its password before sign in

### Reproduction steps

```bash
1. Go to sign in page
3. Scroll down to password
4. See error there is no hid and visible icon.
```

### Screenshots

![DESCRIPTION](LINK.png)
![Screenshot 2024-05-16 224304](https://github.com/krishnaacharyaa/wanderlust/assets/120244528/3c2cccbd-c5d6-42cf-b279-f185eb32eb0a)

**Comment by GOURAVSINGH19** [comment]
@Sukomal07

**Comment by Sukomal07** [comment]
ok i will do it

**Comment by GOURAVSINGH19** [comment]
@wanderlust

**Comment by krishnaacharyaa** [comment]
@GOURAVSINGH19 , kindly let us know the approach and ETA,
@Sukomal07 let us give @GOURAVSINGH19 a chance, 
We can work on the auth ... like the missing things

**Comment by krishnaacharyaa** [comment]
@GOURAVSINGH19 where are you?

**Comment by GOURAVSINGH19** [comment]
yes bro.

**Comment by krishnaacharyaa** [comment]
You were interested in taking this up right? @GOURAVSINGH19 
Still interested? join discord

**Comment by GOURAVSINGH19** [comment]
Yes I am interested..

**Comment by GOURAVSINGH19** [comment]
How I can join your discord (any Link)..

**Comment by krishnaacharyaa** [comment]
Tell us your approach and ETA @GOURAVSINGH19

**Comment by GOURAVSINGH19** [comment]
1.We added a passwordVisible state to manage the visibility of the password.
2.The togglePasswordVisibility function toggles the passwordVisible state when the button is clicked.
3.We replaced the type attribute of the input element with a dynamic expression based on the passwordVisible state, which changes between 'text' and 'password'.
4.Added a button next to the input field that triggers the togglePasswordVisibility function when clicked. The button's text changes dynamically between 'Show' and 'Hide' based on the passwordVisible state.

**Comment by krishnaacharyaa** [comment]
Sure @GOURAVSINGH19 go ahead. How much days will you take ?

**Comment by GOURAVSINGH19** [comment]
today...

**Comment by krishnaacharyaa** [comment]
@GOURAVSINGH19 github readme , you'll find the discord link

**Comment by GOURAVSINGH19** [comment]
Sorry for disturbing you But I need you help while trying push the change it show errors. like this 
![Screenshot 2024-05-19 155708](https://github.com/krishnaacharyaa/wanderlust/assets/120244528/305e7bff-75f2-440b-a787-059855be7e62)

**Comment by krishnaacharyaa** [comment]
You have the answer there @GOURAVSINGH19

**Comment by Tarungupta18** [comment]
Assign me excited to contribute

**Comment by GOURAVSINGH19** [comment]
@krishnaacharyaa  if there is no issue then  you can merge it .

**Comment by krishnaacharyaa** [comment]
There is issue and I have pinged you twice @GOURAVSINGH19 see the PR comments carefully

**Comment by Dhevamuthu** [comment]
Can you please assign me this issue under GSSoC'24 i would like to work on it.

**Comment by GOURAVSINGH19** [comment]
I am sorry but I can't found any pinged issue in my pr comments

**Comment by krishnaacharyaa** [comment]
@Dhevamuthu @Tarungupta18 have you heard of term code of conduct? If not try to understand

**Comment by avilash01** [comment]
Can you please assign this issue to me ?
