### ISSUE TITLE
Readme.md file can be more fascinating 

### ISSUE THREAD

**Issue by Meetjain1** [krishnaacharyaa/wanderlust#263]
### Description

Readme.md file can be more fascinating by adding contributors section, Tech stack section and a working video of our project 
@krishnaacharyaa sir assign this issue to me i will add it 

### Current Behavior

missing sections

### Proposed Enhancement

Will add some sections

### Use Case

Will look good

**Comment by krishnaacharyaa** [comment]
Hi @Meetjain1 
Can you give a figma UI design or overall rough design on how you want to enhance it

Presently we have how to setup the project in 2 places 
1. contributing.md
2. readme

we should have only of the contributing.md

and discord link and figma links should be nicely replaced with the icons and if you are decent with the github things, you can take up later the FAQ section wala github issue aswell.

And also we have to add Gssoc project logo and the youtube link where we have collaboration with TechwithShubham,

So all this how can you nicely structure it nicely is the challenge, I am ready to give it level3 if we work good on it.. rest assured, I just need a very nice onboard experience for the new comers

**Comment by Meetjain1** [comment]
@krishnaacharyaa sure sir I will work on this , and provide you the screenshots of the overall updated readme.md file by adding these things that you mentioned.
can you just provide me the discord , figma links and youtube link of collaboration.

and I would love to take FAQ section issue also . Thankyou

**Comment by krishnaacharyaa** [comment]
And we have to have the redis installation like mongodb different issue you can make this one ...

And apart from YouTube you'll find the links already in the readme 

For YouTube link 🔗https://youtu.be/ANfC1u_N_A0?feature=shared

And the readme UI should be modern and minimalist...
Open to new thoughts and ideas

**Comment by krishnaacharyaa** [comment]
@Meetjain1

**Comment by Meetjain1** [comment]
> And we have to have the redis installation like mongodb different issue you can make this one ...
> 
> And apart from YouTube you'll find the links already in the readme
> 
> For YouTube link 🔗https://youtu.be/ANfC1u_N_A0?feature=shared
> 
> And the readme UI should be modern and minimalist... Open to new thoughts and ideas

@krishnaacharyaa sure sir 

Will remove
~ How to setup section from readme.md

will add
Discord icon , figma link icon 
working video of the project 
Gsso project logo
youtube link of collaboration
and contribuitors section 

right ?

**Comment by Meetjain1** [comment]
@krishnaacharyaa one confusion , How I have to add the collaboration link means what I have to write while placing the youtube link can you please tell also , please tell where should I place it . Thankyou

**Comment by krishnaacharyaa** [comment]
> Remove . How to setup section from readme.md

You have to give link not totally remove 

And spend time and try to understand what can enhance the readme even further

**Comment by Meetjain1** [comment]
> > Remove . How to setup section from readme.md
> 
> You have to give link not totally remove
> 
> And spend time and try to understand what can enhance the readme even further

ok sir sure , yes I will provide the link
sure will think more to enhance the readme further

**Comment by krishnaacharyaa** [comment]
> @krishnaacharyaa one confusion , How I have to add the collaboration link means what I have to write while placing the youtube link can you please tell also , please tell where should I place it . Thankyou

Here be creative and see what fits best ....

What I thought without thinking much was something like 


Collaboration walaa title 
Below a YouTube logo 
Below YouTuber name ...

See my GitHub readme ... You'll sense the minimalist and clarity wala approach and add more idea ...
Let's try something very decent effective and subtle....
I'm open to ideas.... 
Go ahead.....

**Comment by Meetjain1** [comment]
> > @krishnaacharyaa one confusion , How I have to add the collaboration link means what I have to write while placing the youtube link can you please tell also , please tell where should I place it . Thankyou
> 
> Here be creative and see what fits best ....
> 
> What I thought without thinking much was something like
> 
> Collaboration walaa title Below a YouTube logo Below YouTuber name ...
> 
> See my GitHub readme ... You'll sense the minimalist and clarity wala approach and add more idea ... Let's try something very decent effective and subtle.... I'm open to ideas.... Go ahead.....

ok sir

**Comment by krishnaacharyaa** [comment]
@Meetjain1  where are you , gayab XD. Let me know what is the update

**Comment by Meetjain1** [comment]
> @Meetjain1 where are you , gayab XD. Let me know what is the update

Sorry sir, 
Dusre issue mai busy ho gya tha , aaj ho jaayega Readme file update.✌️

**Comment by Meetjain1** [comment]
@krishnaacharyaa sir gssoc ka banner vala section bhi add krna hai kya ?

**Comment by krishnaacharyaa** [comment]
Yes sir @Meetjain1 , I guess already said, why are we again back on requirements?

**Comment by Meetjain1** [comment]
> Yes sir @Meetjain1 , I guess already said, why are we again back on requirements?

sorry sir, missed it.

**Comment by Meetjain1** [comment]
@krishnaacharyaa sir readme.md file is ready

**Comment by krishnaacharyaa** [comment]
Looks good @Meetjain1, we might need a small call to finalize or just raise the PR, let me closely see it.
Kindly remove the embeded website in 2 places and then have project link instead. And we don't need that big GSsoc. 

Just remove the embeded website. and raise PR I'll tell you in details the changes.
But good work, appreciate it. 

I guess we are missing on the link for setting up the project.

**Comment by Meetjain1** [comment]
@krishnaacharyaa can you specify clearly which embeded website you want me to remove from two places.

**Comment by krishnaacharyaa** [comment]
The very first one where you clicked the dark and light mode @Meetjain1  and the  other one which has complete screenshot of the webpage, those 2 parts, the image which has Wanderlust (presently there in the readme) let that be and any other image remove it

**Comment by Meetjain1** [comment]
@krishnaacharyaa second one I have completed that is removed the webpages snapshots that I have added , and the first one is in the gif that I have created that is enabling and disabling of dark mode that part of the gif you want me to remove na ?

also gssoc big banner logo is removed and small logo is attached instead of it .

**Comment by krishnaacharyaa** [comment]
Remove the gif @Meetjain1 yes greate, lets have a pr let me see it thoroughly to tell you better

**Comment by Meetjain1** [comment]
@krishnaacharyaa ohk sure

**Comment by Meetjain1** [comment]
@krishnaacharyaa created PR #304
