### ISSUE TITLE
[FEATURE] To add user profile settings

### ISSUE THREAD

**Issue by MohiniMehta** [krishnaacharyaa/wanderlust#265]
### Description

As a user, I would like the ability to update my email address through the user profile settings after logging into the system. This feature will enhance user experience by allowing users to keep their contact information current, which is crucial for receiving important notifications and maintaining account security. By this feature the user can view his/her details and can also update contact details.

### Use Case

Scenario:
 Profile Management: A user registers with an email address. Over time, the user's email address may change due to switching email providers, changing jobs, or other personal reasons.
 User Experience: Users may find it frustrating if they cannot update their contact details, leading to a negative user experience.

### Proposed Solution

Here is a solution:
1. Add Profile Image in Navbar:
Display the user's profile image in the navbar after they log in.
Make the profile image clickable to redirect the user to a profile update page.

2. Profile Update Page:
Create a new page where the user can update their contact details, including their email address.
Include a form on this page where users can input their new contact information.

3. Form Submission:
When the user submits the form, send a request to the backend with the updated contact details.
Update the user's information in the MongoDB database upon receiving the request.

4. Backend Logic:
Set up an Express route to handle the incoming request from the profile update page.
In the route's controller, validate the input and update the user's details in MongoDB.

### Attachments

![image](https://github.com/krishnaacharyaa/wanderlust/assets/98202405/4aba62a0-e225-40f0-9c37-f0c3c0a1d8fd)
an image of admin profile can be added which can redirect for viewing and updating login details of the user.

**Comment by MohiniMehta** [comment]
I request you to please assign me this task.

**Comment by krishnaacharyaa** [comment]
Violates code of conduct
