### ISSUE TITLE
[BUG] Loader issue at Create Post

### ISSUE THREAD

**Issue by Mayur-666** [krishnaacharyaa/wanderlust#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When create post is clicked a loader appears which is too small and it reduces the overall page height.

### Expected Behavior

The loader should be full length as page (including the footer size).

### Reproduction steps

```bash
1. Go to 'Landing Page'
2. Click on 'Create Post'
3. See small loader
```

### Screenshots

Current loader:-
![Screenshot (558)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/c5e297d6-1cf5-4f01-8c30-e3917fe56805)

Want to add this Loader that i had in one of my projects.

If color combination is not suitable you can give me suggestion regarding that.

![Screenshot (557)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/300ea17e-2924-4854-ad2d-ca6f40aaeec6)

it works like this:-

![sliding_square_loader_view](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/46a4d2b8-2e53-4889-aeb7-7e94b6c02ee9)

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux

**Comment by krishnaacharyaa** [comment]
We have have skeleton for this, like for the main page, we don't want to break the UI/UX consistency by adding these loaders
