### ISSUE TITLE
[BUG] Redirect Icon Color not matches theme.

### ISSUE THREAD

**Issue by Mayur-666** [krishnaacharyaa/wanderlust#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The redirect icon on Latest posts don't change color with the theme change.

### Expected Behavior

For dark theme is should turn to a lighter color.

### Reproduction steps

```bash
1. Go to 'Landing Page'
2. Scroll down to 'Latest Post'
4. See error
```

### Screenshots

![Screenshot (560)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/09ca0ffa-3baa-4deb-9f64-014a18a8a47c)
![Screenshot (561)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/24483242-e3ab-4370-89ce-529e39ef66f4)

### Browsers

Firefox, Chrome, Microsoft Edge, Opera

### OS

Windows, Linux

**Comment by Ashu0216** [comment]
Hi @krishnaacharyaa  , if no one is yet assigned I would like to take on this issue.
Proposed solution : Change the corresponding CSS style to make the redirect button more visible. 
ETA: 1-2 day.

**Comment by krishnaacharyaa** [comment]
@Ashu0216 sure

**Comment by krishnaacharyaa** [comment]
@chaanakyaaM chat here..

**Comment by chaanakyaaM** [comment]
Sure

**Comment by shivansh84ya** [comment]
Hi @Mayur-666 ,
I would like to work on this issue. Could you please assign it to me?

**Comment by krishnaacharyaa** [comment]
Go ahead @shivansh84ya
