### ISSUE TITLE
Fix the homepage bg image long load time

### ISSUE THREAD

**Issue by jjinendra3** [krishnaacharyaa/wanderlust#28]
The background image of a beach scenery behind the logo on the homepage is currently hosted in JPG format. It takes a significant amount of time to load, even on a fast internet connection. To address this issue, I have hosted the image on imgbb in WebP format. The resolution remains the same, but now, due to its WebP format, the image loads quickly, virtually instantaneously. I kindly request you to assign this issue to me.

**Comment by krishnaacharyaa** [comment]
Hi @jjinendra3 , Thank you for finding this issue and wanting to work on that, 
Hear me out, I have an alternate solution. Instead of converting it into WebP format which still has to get it from internet, how about storing it in asset ?
It can get it near to instant without even the need of internet connection

**Comment by jjinendra3** [comment]
I did thought of that but i prefer taking the assets from internet since a website anyway requires an internet connection and lower the overall build size, the better.

**Comment by krishnaacharyaa** [comment]
Yes I agree, that also would be a good approach,  but there is this tread off, that in future if we were to change the image we would have to again  "host the image on imgbb in WebP format", which wont be ideally to do it everytime we think of changing the image. What is your take on this ? 
I am open to your approach as well, I just want to understand which one would be ideally for us in this project

**Comment by jjinendra3** [comment]
Your approach makes more sense for images that might need frequent updates, but it feels a bit unnecessary for an image that is unlikely to change in the near or distant future. But, if you prefer to keep it as an asset, I'm open to that approach as well. No issues.

**Comment by krishnaacharyaa** [comment]
Yeah i too considered the use case of changing the image, we might not do it quite often or as far as I see we would probably never in the near future will touch that as it is just a static image for the app. Lets look on your approach, please feel free to go with your proposed approach :)
