### ISSUE TITLE
[FEATURE]: add codeql workflow for `javascript`

### ISSUE THREAD

**Issue by harmeetsingh11** [krishnaacharyaa/wanderlust#281]
### Description

The repository contains code in `javascript` , it does not have workflow for code scanning. 

### Use Case

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by krishnaacharyaa** [comment]
Don't follow code of conduct

**Comment by krishnaacharyaa** [comment]
@harmeetsingh11 please don't spam the issues. it is very boring to close these, lets kindly respect each others time
