### ISSUE TITLE
[FEATURE]: Integrate Dependabot for Automated Dependency Updates

### ISSUE THREAD

**Issue by harmeetsingh11** [krishnaacharyaa/wanderlust#283]
### Description

Keeping the project's dependencies up to date can be a challenging task, especially when done manually. To streamline and automate this process, we propose integrating Dependabot.

### Use Case

We need to add Dependabot to our project as it will significantly aid in keeping our dependencies current. Once activated, Dependabot will automatically submit pull requests (PRs) whenever there are outdated dependencies identified in our `package.json` file.

This automated approach will enhance our project's stability, security, and overall maintenance by ensuring that we are always using the latest and most secure versions of our dependencies.

### Checklist

- [X] I am willing to work on this issue
- [X] I am a GSSoC'24 contributor

**Comment by krishnaacharyaa** [comment]
Good thought @harmeetsingh11 

> This automated approach will enhance our project's stability, security, and overall maintenance by ensuring that we are always using the latest and most secure versions of our dependencies.

But we don't require, because there are high chances things break if there is a breaking changes, so i am fine having 2yrs old dependency if it just working fine.

Feel free to pick up any other issues
