### ISSUE TITLE
[ENHANCEMENT] The 'Wanderlust' text should be larger

### ISSUE THREAD

**Issue by ayush-848** [krishnaacharyaa/wanderlust#291]
### Description

Wanderlust is the website name so it should standout.

### Current Behavior

It is currently as the same size as the login button

### Proposed Enhancement

I will enlarge the 'Wanderlust' text.

### Use Case

This will make it standout.

### Additional Information/ Attachments

![image](https://github.com/krishnaacharyaa/wanderlust/assets/126975547/4ef35493-c167-415b-9dae-d74bd9fc8057)

**Comment by krishnaacharyaa** [comment]
Are you seriously crazy @ayush-848 ? 
If there was option to block trust me. I would have opted for it on you.
See what is there in code of conduct and understand me.
You can never contribute this way in my project

**Comment by ayush-848** [comment]
@krishnaacharyaa I am really sorry for my unprofessional behaviour. This is my first time taking part in a contest like GSSoC'24.
I will take your inputs wholeheartedly and will study the the code of conduct of any project before any  requesting  "Issue Request".

Its a fault from my end and I will refrain from doing so in the future.

**Comment by krishnaacharyaa** [comment]
That's nice that you acknowledged.  I appreciated that @ayush-848 
Kindly go through https://github.com/krishnaacharyaa/wanderlust/blob/fd11e4b0f43f900a13ae050f63750ec458c303e9/.github/CODE_OF_CONDUCT.md

And join our discord from the readme. We can discuss which issues you can pick up
