### ISSUE TITLE
Refactoring backend using typescript

### ISSUE THREAD

**Issue by DSAghicha** [krishnaacharyaa/wanderlust#3]

**Comment by krishnaacharyaa** [comment]
Please add description, though the title explains the issue :)

**Comment by DSAghicha** [comment]
I would like to implement a SOA using OOPs in TypeScript where the architecture will be like as follows:
![image](https://github.com/krishnaacharyaa/wanderlust/assets/53931676/c7667aac-ac9e-4479-8c27-e58b4cf5695f)

**Comment by krishnaacharyaa** [comment]
Sure, but presently we already have decent folder architecture which has good seperation of concerns as below
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/e3600543-253e-4ba5-ad23-76479000c7c5)

How does project benefit by using the above SOA architecture, because we are not having multiple services even in the near future, so I feel clean architecture would be a perfect fit here in terms of architecture than SOA.

**Comment by krishnaacharyaa** [comment]
For now may be we can refactor the backend to use ts instead of js and leave the architecture for now as suggested in the title of the issue

**Comment by MunavvarSinan** [comment]
Is anyone doing this? If not could you please assign this to me

**Comment by shmbajaj** [comment]
Hey @krishnaacharyaa I can take this and migrate backend in one go to typescript and later on gradually as people get comfortable they can start writing types for respective code.

A single pr to introduce typescript using ts-migrate something.

**Comment by ppriyankuu** [comment]
I see the backend is yet to be converted into typescript. if no one's currently assigned then maybe I can take up the job.

**Comment by krishnaacharyaa** [comment]
Please tell the approach and ETA @ppriyankuu

**Comment by ppriyankuu** [comment]
I can migrate the files to typescript with minimal types, and later as time goes eventually others can start writing their detailed extensive types.

**Comment by krishnaacharyaa** [comment]
Sure please go ahead kindly follow PR guidelines

**Comment by ppriyankuu** [comment]
Sure!!

**Comment by amit429** [comment]
@krishnaacharyaa Can you assign me this issue so i can try to make conversions and please give it a gssoc'24 tag and the level tag

**Comment by krishnaacharyaa** [comment]
@vamsidhar-914 would you like to take this?

**Comment by vamsidhar-914** [comment]
Yeahh sure...I'll be on itt @krishnaacharyaa

**Comment by vamsidhar-914** [comment]
hi @krishnaacharyaa 

update: almost migrated all JS files to TS with all the types included , didnt touched tests as i didnt work on tests before, it might take some time to do,might use some help on the tests

**Comment by krishnaacharyaa** [comment]
Sure @vamsidhar-914, waiting for the PR

**Comment by vamsidhar-914** [comment]
@krishnaacharyaa  opened

**Comment by krishnaacharyaa** [comment]
@shivansh84ya can you take this up?

**Comment by krishnaacharyaa** [comment]
You have to follow 
https://github.com/krishnaacharyaa/wanderlust/pull/408
And #156 you would have to see and then cover the review comments that's it 
@shivansh84ya  let me know if this interests you

**Comment by krishnaacharyaa** [comment]
@shivansh84ya acknowledgement please. If you are not interested someone else will pick this up

**Comment by shivansh84ya** [comment]
Hi @krishnaacharyaa,

I am ready to Refactoring backend using typescript. Could you please provide more details about this issue and any specific guidelines I should follow?

Thank you!

**Comment by krishnaacharyaa** [comment]
> You have to follow #408 and #156 you would have to see and then cover the review comments that's it @shivansh84ya let me know if this interests you

@shivansh84ya .
Best practices of nodejs ts
And our normal contributing guidelines, nothing else apart from that ....!
