### ISSUE TITLE
[BUG Backend get error all field requied and backend add one column fullname but this functionality are not implement in frontend And Also Login And Signup getting error All field are Required.] <title>

### ISSUE THREAD

**Issue by farukh166** [krishnaacharyaa/wanderlust#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)
![image](https://github.com/krishnaacharyaa/wanderlust/assets/112760002/8c234c72-09d1-42d4-aedd-d15fd468f24c)
![image](https://github.com/krishnaacharyaa/wanderlust/assets/112760002/b18be85f-2de6-4382-8308-09b8a328afd6)

**Comment by krishnaacharyaa** [comment]
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/e20bfd57-f1c7-4f49-b086-48f5a82aa272)
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/a0488957-e3ac-4781-83df-610c516df486)


Not seen in the latest https://wanderlust-beta.vercel.app/
