### ISSUE TITLE
Enhance Footer

### ISSUE THREAD

**Issue by Hemashree21** [krishnaacharyaa/wanderlust#335]
### Description

The current footer looks blank and just has the logo and copyright. It will be better to add some links and social media handles for the footer. 
@krishnaacharyaa can you please assign this to me?

![Screenshot 2024-05-16 092104](https://github.com/krishnaacharyaa/wanderlust/assets/138188163/bb4aa97f-e058-4e96-8a1a-34af7c8ab159)

### Use Case

To attract user attention and make the user explore other social media handles as well.

**Comment by krishnaacharyaa** [comment]
Please read code of conduct please @Hemashree21
