### ISSUE TITLE
Add a toggle switch to switch between light and dark mode 

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#36]
We are presently working on default theme #16, but we would be also needing to give option to the user to have manual switch to toggle which influence the theme of the application

**Comment by suryanshsoni120** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by krishnaacharyaa** [comment]
Hi @suryanshsoni120, sorry I totally missed your comment, can you kindly take up some other issue, as @Raghunandan-29 is currently working on this issue...

**Comment by Raghunandan-29** [comment]
I will make changes soon and rasie PR according to Community Guidelines

**Comment by krishnaacharyaa** [comment]
@Raghunandan-29 Yes please
