### ISSUE TITLE
[ENHANCEMENT] <Adding social media icons on the footer>

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [krishnaacharyaa/wanderlust#363]
### Description

Adding social media icons on the footer

### Current Behavior

no social media icons are there

### Proposed Enhancement

add some social media icons like linkedin.youtube,github,etc

### Use Case

adding some social media platform when any one contact with you he/she can contact you

**Comment by RamakrushnaBiswal** [comment]
hi @krishnaacharyaa can you assign it to me?

**Comment by krishnaacharyaa** [comment]
No @RamakrushnaBiswal
