### ISSUE TITLE
[BUG] <signup page>

### ISSUE THREAD

**Issue by deepak9285** [krishnaacharyaa/wanderlust#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sign up with google or github  is not working 
![Screenshot (612)](https://github.com/krishnaacharyaa/wanderlust/assets/83562221/354bc4e1-38d3-45e5-83cc-a4571b16a2b7)
![Screenshot (613)](https://github.com/krishnaacharyaa/wanderlust/assets/83562221/8737af54-f2d8-45ed-9138-5cb7b53613f5)

One more enhancement should that description of various feilds should be shown like how much length of user name should and what are rules for writing the password .
I can fix all these issue please assign me.

### Expected Behavior

Behaviour should be that user can signup through their github account or google account directly .
and user should not fill difficulty in sign up

### Reproduction steps

```bash
1. Go to 'Login'
2. Click on 'continue with Google'
3. Scroll down to 'error page shown'
4. See error 404 error page
```

### Screenshots

![DESCRIPTION](LINK.png)
![Screenshot (613)](https://github.com/krishnaacharyaa/wanderlust/assets/83562221/9ec06899-fb85-4f09-bc83-eb861778dda6)
while clicking on continue with google or github this page is shown .

### Browsers

Microsoft Edge

### OS

Windows

**Comment by RanjanaShenoy** [comment]
Hi @krishnaacharyaa ,
I am interested to contribute and fix this bug. Please assign this bug to me.
I am GSSOC 2024 contributor.
