### ISSUE TITLE
UI - Add User Authentication

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#38]
Please follow the figma design in the readme and then design it responsive for all the 4 devices, mobile, tablet , desktop and above, wouldn't be more effort in making it responsive as tweaks related to padding would be prominent.
create a route `/user-auth` and design the page, make sure to follow the best practices and consistent coding style already being used. 

This should also cover the changes required in the homepage, detailed page and add blog, you can set a dummy flag to switch between authenticated user and user who is not, this will be later bought into life once the backend changes are done.

**Comment by krishnaacharyaa** [comment]
Lets go one at a time @SanjeevKrSingh, appreciate your enthusisam though ;)

**Comment by rohits-web03** [comment]
Hii @krishnaacharyaa 
Would like to work on this issue.Can you assign me?

**Comment by krishnaacharyaa** [comment]
Thank you for your interest @rohits-web03, Kindly join the discord link from the readme. Presently we are focusing on test cases milestone, post that we'll work on auth, for more details about this auth feature, kindly find it in the announcements section in discord :)

p.s: If you are good at UI there are other issues we can aim at, open to discuss in the discord

**Comment by geetanjalichawla** [comment]
can you assign me this issue

**Comment by krishnaacharyaa** [comment]
@geetanjalichawla, can you please let us know the update on this story

**Comment by krishnaacharyaa** [comment]
@geetanjalichawla Un-assigning, because of no response past a week

**Comment by AnirudhMemani** [comment]
I can do it

**Comment by krishnaacharyaa** [comment]
Hi @AnirudhMemani, sure, Can you kindly let me know how much days estimate and your approach to this, 
p.s: For UI you need to use the Figma and react-hook-form, In similar lines to this https://www.youtube.com/watch?v=u6PQ5xZAv7Q

**Comment by AnirudhMemani** [comment]
@krishnaacharyaa 2-3 days

**Comment by krishnaacharyaa** [comment]
@AnirudhMemani , Can you kindly hop on to discord server

**Comment by krishnaacharyaa** [comment]
@AnirudhMemani Because one more guy is wanting to work on this, so it would be better if you guys are at the same place, And I'll know how to delegate and whom to delegate... Or if you both can take some part of the tasks and raise a merged PR

**Comment by AnirudhMemani** [comment]
If he can do it then it's cool. You can talk to him and let me know I'll do whatever he can't do.
