### ISSUE TITLE
Add markdown support for writing blogs

### ISSUE THREAD

**Issue by The-Phoenics** [krishnaacharyaa/wanderlust#384]
### Description

I've seen most of the blogging platforms support markdown to provide users some control over appearance of the content.

### Use Case

It would easier to distinguish heading with general content if used `#` with some text like this for example:

# Heading
This is blog *content*

and various other countless features that markdown offers like bold & italic text, etc.

### Proposed Solution

I would like to try integrating `md-block` library into the project to make the markdown support possible.

**Comment by krishnaacharyaa** [comment]
Kindly close this @The-Phoenics and feel free to work on the already existing issue and kindly closly go through https://github.com/krishnaacharyaa/wanderlust/pull/158 and understand what exactly would you wanna do. 
Once you tell me the exact approach we can assign the orignal issue to you :)
