### ISSUE TITLE
[BUG] Missing Navigation in Detailed page

### ISSUE THREAD

**Issue by dhruv8433** [krishnaacharyaa/wanderlust#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@krishnaacharyaa 

check this out,
there is no navigatio in detailed page

### Expected Behavior

add navigation in detailed page,
so user can easily redirect to particular page and no need to `go back`

### Reproduction steps

```bash
1. Go to 'home page'
2. Click on 'any resort card'
```

### Screenshots

![image](https://github.com/krishnaacharyaa/wanderlust/assets/114583978/4c18ca72-c77e-4e5d-a0d2-43f886335ddb)

### Browsers

Chrome

### OS

Windows

**Comment by vamsidhar-914** [comment]
where exactly you want to navigate in resort card page

**Comment by dhruv8433** [comment]
Not in resort card
We can add global navigation at the top
