### ISSUE TITLE
[FEATURE] Add Privacy page

### ISSUE THREAD

**Issue by dhruv8433** [krishnaacharyaa/wanderlust#386]
### Description

@krishnaacharyaa 

we can add privacy page

### Use Case

A privacy page informs users about how their personal data is collected, used, and protected, ensuring transparency and compliance with legal requirements. It builds trust by outlining data handling practices and users' rights regarding their information.

### Proposed Solution

we can design new route `/privacy-policy` 

### Attachments

![image](https://github.com/krishnaacharyaa/wanderlust/assets/114583978/efc80f9a-359f-4546-80df-df1c07491c18)

**Comment by PrakarshSingh5** [comment]
Please assign this issue to me
