### ISSUE TITLE
[BUG] additional card in detail page

### ISSUE THREAD

**Issue by Varsani2520** [krishnaacharyaa/wanderlust#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in detail page nothing to much 
look like a boring also short information

### Expected Behavior

in detail page ,
we can add the additional card like tourism website or flipkart

for example :we click on shoes then display the shoes related information additionally other shoes also display for user visit more and more website

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)
![image](https://github.com/krishnaacharyaa/wanderlust/assets/137641079/683888f2-73af-40a7-b1c9-38a73cfc4ac4)
like this :
![image](https://github.com/krishnaacharyaa/wanderlust/assets/137641079/dba08b34-8e1b-4fba-a960-93992e174ae4)

**Comment by krishnaacharyaa** [comment]
@Varsani2520  you might have to work on your writing skills, you can take up related blogs section like in the figma for detailed page
