### ISSUE TITLE
improvement in css of login page in mobile view / responsiveness 

### ISSUE THREAD

**Issue by dhairyagothi** [krishnaacharyaa/wanderlust#396]
### Description

![image](https://github.com/krishnaacharyaa/wanderlust/assets/142989448/c377d304-c0c2-4cf0-857f-04e849919d0b)

css of login page in mobile view not look good i can fix it

### Current Behavior

all elements are added on top of page

### Proposed Enhancement

username and password section should be centralized

### Use Case

It will enhance look in mobile view and it will increease ui/ux of website

**Comment by krishnaacharyaa** [comment]
Sure @dhairyagothi you can work on this, Let me know if you still interested in contributing, happy to assign :)

**Comment by krishnaacharyaa** [comment]
And  if you are still interested in working on this project, let me know via the project's discord, I might have some better issues of level 2 and 3 that you could work on !! @dhairyagothi

**Comment by dhairyagothi** [comment]
> Sure @dhairyagothi you can work on this, Let me know if you still interested in contributing, happy to assign :) 

Ya i am interested please assign me

**Comment by krishnaacharyaa** [comment]
Closing as completed
