### ISSUE TITLE
[ENHANCEMENT] Enhancing the UI of the 404 page to match the theme of the website

### ISSUE THREAD

**Issue by AMS003010** [krishnaacharyaa/wanderlust#411]
### Description

Enhancing the UI of the 404 page to match the theme of the website will greatly enhance the user experience

### Current Behavior

The current 404 page does not match the theme of the website. I feel the animation part is not needed.

### Proposed Enhancement

I feel that removing the animation and adding a modern static design to the 404 page which matches the theme of the website would be great.

### Use Case

This would greatly enhance user experience

### Blockers

None

### Additional Information/ Attachments

Please do assign me this issue under gssoc'24

**Comment by krishnaacharyaa** [comment]
I'm all ears @AMS003010, let me know what you wanna propose?

**Comment by krishnaacharyaa** [comment]
By the way if you are still interested in working on this project, let me know via the project's discord, I might have some better issues of level 2 and 3 that you could work on !! @AMS003010

**Comment by AMS003010** [comment]
> I'm all ears @AMS003010, let me know what you wanna propose?

We could make it more user friendly by having an engaging headline like "Lost in Transit?", "Oops, it looks like you took a wrong turn!". Maybe remove the animation entirely ( or replace it with a better one ) and have  a simple vector image as the 404 image. We could also add features like
 - Display a few suggestions for popular destinations, blogs or travel guides.
 - Provide some travel tools like currency convertor, weather forecast etc.

**Comment by AMS003010** [comment]
> By the way if you are still interested in working on this project, let me know via the project's discord, I might have some better issues of level 2 and 3 that you could work on !! @AMS003010

Thanks 😁, I would very much like to work on those issues.

**Comment by shivansh84ya** [comment]
Could you assign this issue to me @krishnaacharyaa ?

**Comment by krishnaacharyaa** [comment]
@AMS003010 you are working on this?

**Comment by AMS003010** [comment]
Nope, I mean I wasn't assigned 😅

**Comment by krishnaacharyaa** [comment]
Yeah, do you wish to work? @AMS003010

**Comment by AMS003010** [comment]
Sure that would be great 😸

**Comment by shivansh84ya** [comment]
Is this issue active? If nobody is working on this issue then I would like to work on it??

**Comment by krishnaacharyaa** [comment]
@shivansh84ya aren't you working on backend typescript?

**Comment by shivansh84ya** [comment]
@krishnaacharyaa I am working on the issue you assigned, but I am encountering many challenges and errors because I am not very familiar with Typescript

**Comment by krishnaacharyaa** [comment]
@shivansh84ya you have 2 PRs for reference 
You have claud ai chatgpt...
Figure out it should be easy
