### ISSUE TITLE
[FEATURE] : Preloader

### ISSUE THREAD

**Issue by chaanakyaaM** [krishnaacharyaa/wanderlust#414]
### Description

The website is awesome, but the website takes few seconds to load the content/images this makes the website appear slow.
I would like to add a preloader to the website, which makes the website look more professional and attractive.

### Use Case

The preloader helps the users wait till the website resources are loaded, which helps the website by not letting the website appear slow and odd.

### Additional Information

would you assign me this issue under GSSOC'24?
Thank you.

### Attachments

![image](https://github.com/krishnaacharyaa/wanderlust/assets/131477601/7b2aeb5e-8962-4be5-9a09-4191c2d92026)

**Comment by krishnaacharyaa** [comment]
What is a preloader? @chaanakyaaM, Because we have shimmer loading already in place

**Comment by krishnaacharyaa** [comment]
By the way if you are still interested in working on this project, let me know via the project's discord, I might have some better issues of level 2 and 3 that you could work on !! @chaanakyaaM

**Comment by chaanakyaaM** [comment]
Can you provide the link of the discord channel.

**Comment by krishnaacharyaa** [comment]
It is the readme @chaanakyaaM

**Comment by chaanakyaaM** [comment]
Ok

**Comment by officeneerajsaini** [comment]
@krishnaacharyaa , if this is not a valid issue, we can close it.
