### ISSUE TITLE
Feature🌟 : Add "Scroll to Top" Button 

### ISSUE THREAD

**Issue by aslams2020** [krishnaacharyaa/wanderlust#416]
### Description

Hey @krishnaacharyaa,
Here is the feature i want to suggest and implement - 

I would like to implement a "Scroll to Top" button that appears when the user scrolls down the page. This button should be prominently displayed and easy to click, allowing users to quickly return to the top of the page with a single click.
The button can be styled to fit the design of the website and could be positioned at the bottom right corner of the viewport.

### Use Case

The "Scroll to Top" button is a common feature on websites that enhances user experience by providing a convenient way for users to return to the top of a long page without having to manually scroll.
the "Scroll to Top" button is a small yet impactful addition that contributes to a seamless and enjoyable browsing experience for your website visitors.

### Proposed Solution

Add an anchor element with appropriate classes and IDs in HTML, apply CSS styles for button appearance, and use JavaScript to handle scrolling events and scroll functionality to the top of the page.

### Attachments

This is where we will add the "Scroll to top" button to improve user experience to be more convienient.

![image](https://github.com/krishnaacharyaa/wanderlust/assets/131389695/229135cb-579a-4841-b802-c3e409dc56dc)

Could you please assing me this issue under GSSOC'24?
I will be happy to contribute to the project.

**Comment by krishnaacharyaa** [comment]
Kindly contribute to other issues, we won't require this feature... Can't find a issue? Join discord
