### ISSUE TITLE
[BUG]: Dimensions of the WebApp lacks Compatability with Small Screen Devices 

### ISSUE THREAD

**Issue by codercake** [krishnaacharyaa/wanderlust#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When accessing the web application on a small screen device, such as a smartphone or tablet, the layout and elements do not adjust properly to fit within the smaller viewport. This results in overlapping elements, text becoming unreadable due to resizing issues, and certain buttons or links being difficult to interact with.

### Expected Behavior

- N/A

### Reproduction steps

```bash
Go to the URL of the web application.
Navigate to the login page (if applicable).
Resize the browser window to simulate a small screen device (e.g., tablet or smartphone dimensions).
Scroll through different sections of the web application, such as the dashboard or settings pages.
Observe how various elements respond to the smaller screen size, including:
Text readability and size.
Button and link accessibility.
Alignment and layout of elements.
```

### Screenshots

Landing Page 
![Screenshot 2024-06-14 140243](https://github.com/krishnaacharyaa/wanderlust/assets/117517206/9d6ac177-bd82-448e-bfcd-a01154a4ca88)

### Browsers

Chrome, Microsoft Edge

### OS

Windows

**Comment by krishnaacharyaa** [comment]
<img width="480" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/592ac41a-8c81-44c8-ad8d-370c1cec4d91">

I liked the details description, really appreciated, but this seems good to me, might be some bug in your system, I agree the wanderlust title and logo could be a bit more small relatively, but it is a different issue altogether than this issue....

And we are assuming the width should be a min of 375px

**Comment by krishnaacharyaa** [comment]
Thank you @codercake

**Comment by krishnaacharyaa** [comment]
By the way if you are still interested in working on this project, let me know via the project's discord, I might have some better issues of level 2 and 3 that you could work on !! @codercake
