### ISSUE TITLE
[ENHANCEMENT] Adding user type in frontend

### ISSUE THREAD

**Issue by devsharmagit** [krishnaacharyaa/wanderlust#418]
### Description

Right now frontend does not have a user type in the types folder. User types need to be added in the types folder for better type checking. and prevent future bugs.

### Current Behavior

No user type in frontend types folderthe folder

### Proposed Enhancement

add a user type on frontend type folder and use it everywhere.

### Use Case

This will prevent future bugs and clean code format.

**Comment by AMS003010** [comment]
Hello @krishnaacharyaa 🤗

Please do assign me this issue under gssoc'24

Thank you

**Comment by AMS003010** [comment]
@krishnaacharyaa I have made the PR
Please do review it.

**Comment by AMS003010** [comment]
@krishnaacharyaa  I have made the PR
Please do review it.
Sorry 😅 for the delay, I was doubtful as to if the type should be applied for the mongo schema as well.

**Comment by AMS003010** [comment]
@krishnaacharyaa I have made the fix, please do review it
