### ISSUE TITLE
[ENHANCEMENT] Add post editing functionality to the frontend.

### ISSUE THREAD

**Issue by devsharmagit** [krishnaacharyaa/wanderlust#419]
### Description

There should be a way for the user to edit their post. Backend API is done for this. Now just the frontend part is remaining.

### Current Behavior

There is no way to edit user posts on the frontend

### Proposed Enhancement

![Screenshot 2024-05-27 093737](https://github.com/krishnaacharyaa/wanderlust/assets/109821078/2c7008bb-a446-4f48-b400-c3414402a7bf)

take reference from the above and make separate components
make separate route for edit the post
also check if user own the post or not (if not then redirect them with error message)

### Use Case

this will allow the user to edit their own posts

**Comment by Aradhyajha** [comment]
Hii @krishnaacharyaa sir, please assign me this issue no #419.. i will solve this issue as soon as possible..
![edit](https://github.com/krishnaacharyaa/wanderlust/assets/130289875/9214b6c1-84ef-4566-bfb0-a2162fa36488)
 
To add post editing functionality to the frontend, include an "Edit" button for each post that toggles an edit form containing input fields for the post's title and content. Use JavaScript to handle form submissions, sending the updated data to the server via a PUT or PATCH request. Ensure the backend processes the update and returns a success response. Upon successful update, use JavaScript to update the post content on the frontend without reloading the page, providing a seamless editing experience.

**Comment by Aradhyajha** [comment]
Hii @krishnaacharyaa sir, please assign me this issue no .#419 i will solve this issue as soon as possible..
To add post editing functionality to the frontend, include an "Edit" button for each post that toggles an edit form containing input fields for the post's title and content. Use JavaScript to handle form submissions, sending the updated data to the server via a PUT or PATCH request. Ensure the backend processes the update and returns a success response. Upon successful update, use JavaScript to update the post content on the frontend without reloading the page, providing a seamless editing experience
![edit1](https://github.com/krishnaacharyaa/wanderlust/assets/130289875/1f3be79d-baf2-4f1f-9b5b-969d7870e5c1)

**Comment by krishnaacharyaa** [comment]
You are violating code of conduct @Aradhyajha , and it is being worked by @devsharmagit

**Comment by Aradhyajha** [comment]
Ok sir

**Comment by krishnaacharyaa** [comment]
@Aradhyajha violating conduct by using ai to write the answers for you ! And if you actually are interested in learning join discord server, lets see what best we can do :)

**Comment by Aradhyajha** [comment]
Yes sir I have actually interested in to work on this project if any work
for me please assign it to me and really sorry sir if I did something wrong

**Comment by krishnaacharyaa** [comment]
@devsharmagit by when can we expect this to be raised?
