### ISSUE TITLE
Close Icon on Login and Sign-in Page

### ISSUE THREAD

**Issue by Shashanktriathi1703** [krishnaacharyaa/wanderlust#420]
### Description

*  When users click on the login and sign-in buttons, they often find it difficult to go back to the previous page. To solve this problem, I recommend adding a close icon. This will help users easily navigate back to where they were browsing before.

### Use Case

* Adding a close icon to the login and sign-in buttons can indeed improve user experience by providing a more intuitive way for users to navigate back to the previous page. This feature can be especially useful for users who may be unfamiliar with website navigation or have difficulty finding their way back to the previous page.

* By incorporating a close icon, users can quickly dismiss the login or sign-in prompt and return to their previous browsing activity without getting lost or confused. This small but important detail can enhance the overall usability of your website and contribute to a more seamless user journey.

### Additional Information

- [x] I am an Open Source Contributor in GSSOC'24.

**Comment by Shashanktriathi1703** [comment]
Allow me to work on this issue under GSSOC' 2024 @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
What are you talking? Have you checked out our application? @Shashanktriathi1703

**Comment by Shashanktriathi1703** [comment]
Yes, I have seen your  **[@krishnaacharyaa](https://github.com/krishnaacharyaa/wanderlust)**  Application that's why I raised the issue.
 * Sign in:
![issue](https://github.com/krishnaacharyaa/wanderlust/assets/105815482/151d3add-8755-4b19-a3a8-27796bfcc296)

* Sign up:
![issue1](https://github.com/krishnaacharyaa/wanderlust/assets/105815482/f2a87d85-1673-456c-aae8-34befa6eb989)
