### ISSUE TITLE
[FEATURE] Scroll to Top button

### ISSUE THREAD

**Issue by MuraliDharan7** [krishnaacharyaa/wanderlust#424]
### Description

I want to add Scroll to Top Button in the website.

### Use Case

This would help the users to take them to the top of the website. 

### Proposed Solution

By adding this button, by one click they can achieve the solution which is going to top of the page.

**Comment by shivansh84ya** [comment]
could you assign this issue to me?

**Comment by Yashop181** [comment]
I would like to work on this issue. Could you please assign it to me?
