### ISSUE TITLE
[ENHANCEMENT] Making the Footer responsible

### ISSUE THREAD

**Issue by MuraliDharan7** [krishnaacharyaa/wanderlust#425]
### Description

I want to enhance the footer of the website.

### Current Behavior

Now the footer has only copyrights description. This needs to have links and other sections as well. 

### Proposed Enhancement

I will add some links and the logo of the social media platforms and other newsletter section and some extra links.

### Use Case

This will help the users quickly go through other section and find the thing they want.

Assign this to me under GSSoC'24.

**Comment by Ankit389** [comment]
hello sir @krishnaacharyaa  i want to wok on this issue please assign this task to me 
Making the footer responsible will finish it tomorrow

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me?

**Comment by krishnaacharyaa** [comment]
Concurrently 2 things you wanna work on ? @shivansh84ya

**Comment by MuraliDharan7** [comment]
> Closing as done

Why did you close this issue.

**Comment by krishnaacharyaa** [comment]
@MuraliDharan7 I guess I have already commented !! and it says why I have closed ?!!
https://wanderlust-beta.vercel.app this might answer your question
