### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by MetiUmashri** [krishnaacharyaa/wanderlust#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The login page doesn't have show hide password icon so would like to work on that.

### Expected Behavior

Will make sure that the login page works perfectly with necessary features suggested above. Kindly assign this issue to me.

### Reproduction steps

```bash
Will make sure that the login page works perfectly with necessary features suggested above. Kindly assign this issue to me.
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### OS

Windows

**Comment by krishnaacharyaa** [comment]
> The login page doesn't have show hide password icon so would like to work on that.

Login has, sign up doesn't
@MetiUmashri

**Comment by MetiUmashri** [comment]
yep will make changes accordingly
