### ISSUE TITLE
[FEATURE] :Want to Add signin with google button

### ISSUE THREAD

**Issue by nishant0708** [krishnaacharyaa/wanderlust#429]
### Description

want to add signin with google button

### Use Case

it will make login /signup easier

**Comment by krishnaacharyaa** [comment]
Okay go ahead @nishant0708 UI is already in place you have to uncomment, just take care of the backend

**Comment by krishnaacharyaa** [comment]
@nishant0708 working?

**Comment by NirbhaySingh74** [comment]
i want to work on it but i am facing problem in redis and not able to connect mongodb locally??

**Comment by nishant0708** [comment]
Yes I am I will raise pr by tomorrow

**Comment by siddharthisrani** [comment]
Hii @krishnaacharyaa  can i add the  Google login Button?

**Comment by krishnaacharyaa** [comment]
@siddharthisran

**Comment by krishnaacharyaa** [comment]
@siddharthisrani google button UI is already in place but commented out, let me know if you want to integrate by working backend

**Comment by siddharthisrani** [comment]
@krishnaacharyaa  Yes, I would like to work on integrating the backend for this feature.

**Comment by krishnaacharyaa** [comment]
@siddharthisrani how far are we?

**Comment by siddharthisrani** [comment]
@krishnaacharyaa Yes added the login functionality with google , working good but need to change in Header.tsx so that it show the CreatePost and Logout buttons ... And want  to Ask that can i change Link Tag into button tag? the "to"  path is creating problem for me

**Comment by krishnaacharyaa** [comment]
> And want to Ask that can i change Link Tag into button tag? the "to" path is creating problem for me

If there is no visual changes, go ahead ... but give little more efforts to see if it is possible using Link alone
@siddharthisrani

**Comment by siddharthisrani** [comment]
Hii @krishnaacharyaa 
1. I stuck on one thing that when i login with Google and try to click on Create post it navigates me to sign page says Unautherised .
2. Second should i Create new schema model for Google user Because i need to make some field Required False.

**Comment by krishnaacharyaa** [comment]
> I stuck on one thing that when i login with Google and try to click on Create post it navigates me to sign page says Unautherised .

It's because of not providing acces_token, figure out why it  is saying unauthorized and give it the token , for that you will have to first create a token

 > to make some field Required False.
 
 What is that field, and why do you need to mark it as false?

**Comment by siddharthisrani** [comment]
Fields are FullName, username and Password because Google login doesnt contain this field for This i have to make new  seperate Schema for Google login user

**Comment by krishnaacharyaa** [comment]
@Sukomal07 can you please validate this

**Comment by Sukomal07** [comment]
@siddharthisrani I think the new schema is not required for Google login. Make passwords optional, and one thing can you  implement Google Login with Passport. js

**Comment by siddharthisrani** [comment]
@Sukomal07 Implemented with Passport only ! before i was doing with express-session now tried with token too still getting issue ,new issue was It loads infinte after clicking on Create Post... @krishnaacharyaa  I am starting from Scratch now .

**Comment by krishnaacharyaa** [comment]
@siddharthisrani any progress?

**Comment by siddharthisrani** [comment]
@krishnaacharyaa Stuck on other work and was waiting for your reply...Starting from today apology for the delay.

**Comment by krishnaacharyaa** [comment]
> was waiting for your reply

What reply where you waiting? I just didn't acknowledge, saw this message
> @krishnaacharyaa I am starting from Scratch now .

What reply did it demand? am i missing something? It was a statement

**Comment by siddharthisrani** [comment]
@krishnaacharyaa I was waiting for your comformation too , their was a quite missunderstanding and i was engaged with other project.

**Comment by krishnaacharyaa** [comment]
You are doing it now ? @siddharthisrani or how is it

**Comment by siddharthisrani** [comment]
@krishnaacharyaa Yes i am working on it.
