### ISSUE TITLE
[ENHANCEMENT] Add signup button and linked with signup page

### ISSUE THREAD

**Issue by theashikagupta** [krishnaacharyaa/wanderlust#431]
### Description

Create a signup button near login button then linked it with signup page

### Current Behavior

There is no signup button

### Proposed Enhancement

Add a signup button and link it with signup page 

### Use Case

New Users can directly click on signup button instead of login button

### Additional Information/ Attachments

![Screenshot 2024-06-25 122418](https://github.com/krishnaacharyaa/wanderlust/assets/136061047/c11d8414-5bfd-4c66-bd85-ce41e5beaf9d)

**Comment by theashikagupta** [comment]
@krishnaacharyaa  Kindly assign me this issue under GSSOC'24

**Comment by krishnaacharyaa** [comment]
Thank you @theashikagupta but once he gets in he gets the signup option, that suffices for now, we wouldn't be needing this

**Comment by theashikagupta** [comment]
Okay no problem
