### ISSUE TITLE
[BUG] header should be displayed properly in signup and login page 

### ISSUE THREAD

**Issue by kapilG0** [krishnaacharyaa/wanderlust#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction steps

```bash
Header should be showing properly in mobile
```

### Screenshots

![DESCRIPTION](LINK.png)
![Screenshot_20240625_233930](https://github.com/krishnaacharyaa/wanderlust/assets/59639410/8d3ec380-46da-426d-9a9c-1f32f644afca)

**Comment by krishnaacharyaa** [comment]
@kapilG0 doing?

**Comment by kapilG0** [comment]
> @kapilG0 doing?

Hello @krishnaacharyaa I will start from tomorrow please give me sometime
