### ISSUE TITLE
[BUG] Eye toggle

### ISSUE THREAD

**Issue by AkhilaSunesh** [krishnaacharyaa/wanderlust#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Location: login and sign up page
When this eye is selected the password should be visible. The current case does the exact opposite. This creates a sense of confusion.
![image](https://github.com/krishnaacharyaa/wanderlust/assets/140897461/bbc2a721-43fb-4438-b5d5-8cdc529d08f4)

### Reproduction steps

```bash
Eye toggle
eye/eye-slash
```

**Comment by krishnaacharyaa** [comment]
Working as expected please check again,
