### ISSUE TITLE
[FEATURE] ADDING BEM NAMING CONVENTION

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [krishnaacharyaa/wanderlust#439]
### Objective
I want to add the BEM naming convention . 

### what is BEM Naming Convention
It is a known fact that the right styleguide can significantly increase development speed, debugging, and the implementation of new features in legacy code. Sadly, most CSS codebases are sometimes developed without any structure or naming conventions. This leads to an unmaintainable CSS codebase in the long term.

### Use Case

The BEM approach ensures that everyone who participates in the development of a website works with a single codebase and speaks the same language. Using proper naming will prepare you for the changes in design of the website.

### Proposed Solution

GIVING BEM CLASS NAMES TO EVERY CLASSES 

### Attachments

![Screenshot 2024-06-28 092813](https://github.com/krishnaacharyaa/wanderlust/assets/118350936/044829b3-7d3c-4418-96a2-d23fe6e0e65b)

**Comment by krishnaacharyaa** [comment]
Bhai Bhem we are using tailwind-css, hope they are following it :)
Leave all this , and seriously get to know stuffs yaar, kaha for this stupid gssoc points you are wasting your precious time, 
Agar actual Mei sikhna hei, tho project setup kart, peel dekho project kya hei and the codebase, then message me on discord group. message me if only you are actually interested in learning, if this leaderboard is too important to you, don't join the group :)
All the best
@Ayushmaanagarwal1211

**Comment by krishnaacharyaa** [comment]
Same comment as https://github.com/krishnaacharyaa/wanderlust/issues/439#issuecomment-2196229831 @MuraliDharan7

**Comment by Ayushmaanagarwal1211** [comment]
@krishnaacharyaa  yes bro my bad but  but actually meine kafi sare tabs khol rkhe the uski vjh se glti se issue raise krte time kisi aur ka code dekhliya usmien classes thi to mujhe aisa lga ki classes use ki hein tbhi meine issue raise krdiya .

**Comment by krishnaacharyaa** [comment]
Nahi no problem bhai @Ayushmaanagarwal1211 , I know you are spamming multiple projects, even  if you do fine. But ground reality bool ra hu, aapko choodtaa hu decision lene kaa, Do you want a leaderboard rank which no one gives a damn about, or accha knowledge from which you can land jobs :)

This is coming from a guy you has gold model in Btech CS, and same guy who is joining Zomato in couple of weeks.
Dekho what you wanna do 
@shivansh84ya @MuraliDharan7 same comment to you both swell

**Comment by MuraliDharan7** [comment]
> Nahi no problem bhai @Ayushmaanagarwal1211 , I know you are spamming multiple projects, even if you do fine. But ground reality bool ra hu, aapko choodtaa hu decision lene kaa, Do you want a leaderboard rank which no one gives a damn about, or accha knowledge from which you can land jobs or freelance :)
> 
> This is coming from a guy you has gold model in Btech CS, and same guy who is joining Zomato in couple of weeks. Dekho what you wanna do I'm here if you seriously wanna learn :) but please don't randomly raise issues and say I want to work on them @shivansh84ya @MuraliDharan7 same comment to you both swell

In Zomato as a Technical Lead? haha

**Comment by krishnaacharyaa** [comment]
@MuraliDharan7 
> In Zomato as a Technical Lead? haha

This whole project is built on the concept of helping people and I have quite a work in life to do which fetches me handsome money, I don't even get paid to give you insights of real life and help you people.
IF you don't want real truth or can't accept it, the least I expect you to zip your mouth. Here I never intended to brag about me. But if that's the only thing if you are able to take away. May God Save you !!

Anyways all the best, for you if not this project You'll get thousand others, but please don't use sarcasm and make fun with people who actually want something better from you. It really hurts.

**Comment by krishnaacharyaa** [comment]
And @MuraliDharan7 best of luck in telling to interviewer that you added scroll to top feature in 100 projects, hopefully he'll get impressed. Anyways it is better than gold medal and Zomato technical lead ;)
<img width="1262" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/0362bd6d-e9dc-451b-aeba-287e51a64b69">
<img width="861" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/60bd3733-55ec-4178-af7a-3e92e46861d5">

Enough of lessons for today, enjoy life !!

**Comment by MuraliDharan7** [comment]
@krishnaacharyaa  ThankYou for your guidance so far, you have said the right thing, I think I have been doing Open Source in wrong way. Now I learnt from you, But you should not have said about the zomato at all and other things as well. It was better if you really said about the contribution rule alone not other silly stuffs. Anyway have a great era.
