### ISSUE TITLE
[FEATURE] REMOVING UNWANTED CSS 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [krishnaacharyaa/wanderlust#440]
### Description

I want to remove the unwanted css from the files 
Unwanted css will increase the size of the file , complexity of the file and also create unwanted bugs .

### Use Case

This will surely help to optimize the code

**Comment by krishnaacharyaa** [comment]
Kehanaa kyaa chaaraa bro? @Ayushmaanagarwal1211

**Comment by Alishah572** [comment]
can you assign it to me.
