### ISSUE TITLE
[BUG] Absence of a Proper Loading skeleton for the AddBlog Section

### ISSUE THREAD

**Issue by AMS003010** [krishnaacharyaa/wanderlust#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Present  Loader widget is unresponsive and not matching the website theme
![Image](https://media.discordapp.net/attachments/1223846668127174717/1257014689867497505/image.png?ex=668f63e8&is=668e1268&hm=2a3c87dcb96e60ff665d95a5a2ab91bc1d27fa536ebe323abd4767fd7f2578d8&=&format=webp&quality=lossless&width=1842&height=950)

### Expected Behavior

The AddBlog section should have a proper loading skeleton that is responsive and theme accurate.

### Reproduction steps

```bash
1. Login in
2. Click on Add Blog button
3. Notice the error
```

### Screenshots

Proposed design
![Image](https://media.discordapp.net/attachments/775677854629101581/1260616019215388884/Screenshot_2024-07-10_204403.png?ex=668ff7a8&is=668ea628&hm=2d065e0eaefccf72fb0ca112ab141fb5b465acc23db2d640f004634e275d71c9&=&format=webp&quality=lossless&width=1542&height=950)

### Browsers

Chrome

### OS

Windows

**Comment by samr874** [comment]
May I know who is working on this bug ?
Is this project still active?

**Comment by AMS003010** [comment]
I'm actually working on this issue

**Comment by AMS003010** [comment]
@krishnaacharyaa
It would be great 😸 if you could assign the GSSOC label and the level label as well
