### ISSUE TITLE
Handle middleware errors 

### ISSUE THREAD

**Issue by shivam-sharma7** [krishnaacharyaa/wanderlust#46]
### Description

The error handling middleware allows us to separate our error logic and send responses accordingly. The next() method we discussed in middleware takes us to next middleware/route handler. For error handling, we have the next(err) function.

### Use Case

During development if we will test our API's and if there happen something wrong then it will help you to identify the problem with stack trace.

**Comment by shivam-sharma7** [comment]
@krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
Hi @shivam-sharma7, this directly is related to  https://github.com/krishnaacharyaa/wanderlust/issues/1 and implements the solution which is already proposed in this, kindly pick other issue as previously clearly specified couple of times. 

Thank you
