### ISSUE TITLE
[ENHANCEMENT] Add loading screen in the home page while posts are loading

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#47]
### Description

We can have a shimmer loading screen mocking all the cards visible in the home page like , featured card, categories and latest post so that there wouldn't be a blank screen when the posts are loading

### Current Behavior

Presently there is a blank screen appears, and then once the posts are loaded then the "All Blog Post" heading is pushed to fill the contents

https://github.com/krishnaacharyaa/wanderlust/assets/116620586/2aef85f6-bbfd-4eeb-bef8-79fa3a6f13e9

### Proposed Enhancement

We can have shimmer effect component while loading instead of simple loading bar, preferably using shadcn's skeleton component.

### Use Case

Helps in better UX, and there wouldn't be a empty screen when the posts are yet to load

**Comment by chinmaykunkikar** [comment]
A suggestion about the shimmer effect component - since we're using Tailwind, we can use shadcn-ui's skeleton component. It's easier to implement and offers loads of flexibility.

**Comment by krishnaacharyaa** [comment]
Sure @chinmaykunkikar that's a perfect idea, will update the PR to reflect the same :)

**Comment by krishnaacharyaa** [comment]
Hi @hemant14050, do you wish to work on this ? Please let us know, happy to take your assistance on this :)

**Comment by hemant14050** [comment]
> Hi @hemant14050, do you wish to work on this ? Please let us know, happy to take your assistance on this :)

Hello @krishnaacharyaa, After reviewing the enhancement details, I am interested in working on this task. Could you please assign it to me?
