### ISSUE TITLE
[ENHANCEMENT] Add button inside image url input to generate random images

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#49]
### Description

Presently, people who want to test are not patient enough to make efforts to find a valid image from the website and then upload, so they normally end up in something like `demo.png`, our regex passes and then image is not loaded in the home page, so we need to have array of 10 perfect working images preferably of webP fromat as it loads faster, and when `generate random` button is clicked one of the 10 images url form the array should get auto filled.

### Current Behavior

We can have invalid images like demo.png when creating a post

### Proposed Enhancement

Add a button `generate random image url` in the textbox of image url which autofills with the perfect image from array of image urls 

### Use Case

It helps in enhancing UI of the app, so we don't see broken images in the app

**Comment by jjinendra3** [comment]
Please assign this issue to me:)

**Comment by jjinendra3** [comment]
Hi @krishnaacharyaa , thank you for assigning the issue, i was thinking maybe we can add a feature such that the user can see and select the image from the array of 10 images instead of randomizing. Please lmk your thoughts on this.

**Comment by krishnaacharyaa** [comment]
Thats a nice idea @jjinendra3, But I was thinking it as a small feature before we support uploading the post. You have a point, so maybe we can do something like a modal which pops up when you click "upload image" button, in that modal we can have 2 tabs, 1st one the template, where we would have may be 3x3 images and in the next tab we can allow user to choose image from their system and then upload, you can leave the second tab with a placeholder and take up in new feature ticket.
Let me know your thoughts, this would require figma UI for you though ...

**Comment by jjinendra3** [comment]
Since we are making it a feature just for some time and will soon shift to the uploading method, i think randomizing would be better, i think figma design for a small feature that too for sometime will not be worth it. But i'm open for both the approach.

**Comment by krishnaacharyaa** [comment]
But we can try this @jjinendra3, in use case where people are happy with uploading the images which are ready to select rather than finding it in their system or say they don't have a perfect photo for the blog post, We can have around 20 optimised images in webP form and randomly generate 9 from which user can select, so that we can reduce the repetition of a single image in all the post in the near future :), but it is not necessary for now, direct picking of 9 should also do.

@chinmaykunkikar, what do you think about https://github.com/krishnaacharyaa/wanderlust/issues/49#issuecomment-1795196233

**Comment by chinmaykunkikar** [comment]
This sounds good. We can take inspiration from Google's approach to this and make a simpler version that suits the project's needs.

![image](https://github.com/krishnaacharyaa/wanderlust/assets/6230769/a2af4189-cc46-43ed-95be-e96e8f04a108)

![image](https://github.com/krishnaacharyaa/wanderlust/assets/6230769/f519df67-56cf-4144-8d4b-33e881be4ce8)
