### ISSUE TITLE
Adding Unit test cases for the backend

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#5]
Presently we do not have any test cases written in the application which ensures security, as the project grows in the size there are high chances that the application can break. So adding relevant test cases would be very handy.
Mostly likes framework like jest can be used to achieve this, if any other framework which is better than this, we can discuss and proceed.

**Comment by krishnaacharyaa** [comment]
Hi @hemant14050 can you kindly look into this, once we get done with this we can aim at user authentication issues. Tests would mainly involve API tests and you research a little on the best practices and implement the same, kindly let me know if I can assign this to you :)

**Comment by hemant14050** [comment]
> Hi @hemant14050 can you kindly look into this, once we get done with this we can aim at user authentication issues. Tests would mainly involve API tests and you research a little on the best practices and implement the same, kindly let me know if I can assign this to you :)

Hi @krishnaacharyaa,
I appreciate the opportunity to work on adding unit test cases for the backend. I'm new to writing test cases and eager to learn. Could you please share some resources or guidelines to help me get started? Your support would be invaluable.

**Comment by krishnaacharyaa** [comment]
Sure @hemant14050, glad that you asked, Give me sometime, I'll get back to you with some useful links, you can take it from there

**Comment by krishnaacharyaa** [comment]
Hi @hemant14050, I guess you have already figured out, if haven't already figured out these are some useful resources I found, which we can follow
https://blog.logrocket.com/node-js-express-test-driven-development-jest/
https://semaphoreci.com/blog/unit-tests-nodejs-jest

And let us also get code coverage https://stackoverflow.com/questions/24825860/how-to-get-the-code-coverage-report-using-jest
Let us keep it simple and test the following 
1. mongodb db
2. rest api
I think this would be primarily, if you have any more suggestions, happy to consider,
You can even consider exploring a little in integration testing as it will be mostly aggregation of this, so you can aim at 2 issues at once, 
Feel free to ping me anytime you need & now we can even use discussions tab to discuss :)
