### ISSUE TITLE
Introduce slugs to blog post URLs to make sharing easier

### ISSUE THREAD

**Issue by kuldeepjambhulkar** [krishnaacharyaa/wanderlust#55]
### Description

Currently, when I click on a post, the app routes to "/details-page" & displays the clicked post.

Now, if I want to share the post, naturally, I'll copy the URL & send it to the other person. 
Problem here is that, every post is having the same URL (which is [wanderlust-beta.vercel.app/details-page](https://wanderlust-beta.vercel.app/details-page)) 
& as of now if you go to that link, it throws 404.

To solve this, we can use techniques like using the ID of the post in URL, or maybe using something called "slug"

Current URL 
![image](https://github.com/krishnaacharyaa/wanderlust/assets/89466207/2a5b264d-f984-4cb3-a325-5823b361e665)

What I'm suggesting
![image](https://github.com/krishnaacharyaa/wanderlust/assets/89466207/30538ba6-3aae-477e-9b25-47ab210d62f6)

### Use Case

As a reader of the blog,
It would be helpful to get the appropriate link of posts
So that it can be shared with other readers

**Comment by chinmaykunkikar** [comment]
Thanks for the issue. I have rewritten the title for more clarity.

**Comment by kuldeepjambhulkar** [comment]
@krishnaacharyaa 
Came across this new defect & I think it is related to this feature's implementation.

Here's the bug : 

Open any post & copy it's URL.
Paste the URL in new tab
we get 404

The other way is to open any post & refresh the tab itself, we get 404

![image](https://github.com/krishnaacharyaa/wanderlust/assets/89466207/57c986c5-8564-40ea-92db-143309b02cb4)
