### ISSUE TITLE
[ENHANCEMENT] <UI Mobile Responsive> 

### ISSUE THREAD

**Issue by Shashmit** [krishnaacharyaa/wanderlust#59]
### Description

Currently the Button On the page is not responsive on all the type of devices and the button itself is used in many places. Hence I would like to propose a button prop and making the Navbar more responsive.

### Current Behavior

<img width="1006" alt="Screenshot 2023-11-20 at 15 21 39" src="https://github.com/krishnaacharyaa/wanderlust/assets/70282239/2c5da6b5-b856-463c-ab94-7881faef664e">

### Proposed Enhancement

<img width="1006" alt="Screenshot 2023-11-20 at 15 22 00" src="https://github.com/krishnaacharyaa/wanderlust/assets/70282239/355d9a45-c71e-4096-b6ea-3008225e1c35">
<img width="1006" alt="Screenshot 2023-11-20 at 15 23 04" src="https://github.com/krishnaacharyaa/wanderlust/assets/70282239/77faf743-074e-4b3a-bf6d-3db885e1cd48">

### Use Case

This way the button component will allow better reusability of code and cleaner readability. As well as less code on places where other components play vital roles.

**Comment by krishnaacharyaa** [comment]
Hi @Shashmit, 
We already have the corresponding issue about the Home page UI https://github.com/krishnaacharyaa/wanderlust/issues/13
Can you kindly look into this.

And if you wanna work on it, please let us know the approach, so that we can assign it to you, so that you can start working :)
