### ISSUE TITLE
Design Logo For wanderlust website

### ISSUE THREAD

**Issue by SankalpHaritash21** [krishnaacharyaa/wanderlust#63]
### Description

Currently Wanderlust don't have any logo. Aim is to design a logo for wanderlust.

### Current Behavior

We need a website Logo to grabs attention, and good first impression to the user.

### Proposed Enhancement

We will use canva to design a logo for website which showcase and attract users.

### Use Case

This will help user to trust our website and will help to create good first impression

**Comment by krishnaacharyaa** [comment]
Done
