### ISSUE TITLE
Adding integration test in the backend

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#7]
Presently we do not have any test cases written in the application which ensures security, as the project grows in the size there are high chances that the application can break. So adding relevant test cases would be very handy.
Mostly likes framework like jest can be used to achieve this, if any other framework which is better than this, we can discuss and proceed.

**Comment by shmbajaj** [comment]
> Presently we do not have any test cases written in the application which ensures security, as the project grows in the size there are high chances that the application can break. So adding relevant test cases would be very handy. Mostly likes framework like jest can be used to achieve this, if any other framework which is better than this, we can discuss and proceed.

Hey @krishnaacharyaa I want to know more on `security` angle?
> How Automation testing helps with security?

**Comment by krishnaacharyaa** [comment]
Can you come again @shmbajaj, didn't get you ...
By security I meant : "assuring the code doesn't break at a long run", in this way I meant security. 

> How Automation testing helps with security?

Didn't get this? Are you referring this from elsewhere or how is it, what is this reference to ...

**Comment by krishnaacharyaa** [comment]
The PR https://github.com/krishnaacharyaa/wanderlust/pull/89 closes this issue, hence closing this issue as resolved
