### ISSUE TITLE
Jest framework configuration for unit test cases

### ISSUE THREAD

**Issue by yeshwanth235** [krishnaacharyaa/wanderlust#72]
### Description

Jest is a JavaScript testing framework with a focus on simplicity. Jest is designed to make it easy to write and run tests, and it comes with a number of features that make it a powerful testing tool.
- Will configure the jest framework in the project
- will write test cases for one of the files (add-blog.tsx).

### Use Case

Helps maintain the code quality

**Comment by yeshwanth235** [comment]
Hey @krishnaacharyaa please assign this issue to me

**Comment by krishnaacharyaa** [comment]
@yeshwanth235, can we get updates on this

**Comment by krishnaacharyaa** [comment]
https://github.com/krishnaacharyaa/wanderlust/pull/84 handles this
