### ISSUE TITLE
jpg/png/webp was written in the Blog cover image  but not working 

### ISSUE THREAD

**Issue by geetanjalichawla** [krishnaacharyaa/wanderlust#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to post the blog with the provided image link [https://i.ibb.co/KLwfZzG/Maldives-1024x767.webp](url) the system returns a 400 error. 

Upon inspecting the error message, it states: Image `URL must end with .jpg, .jpeg, or .png.` The platform or form appears to only accept image links with these specific file extensions. However, the provided image link has a **webp extension**, causing the submission to fail.

**Test Case**
`{"title":"test","authorName":"test","imageLink":"https://i.ibb.co/KLwfZzG/Maldives-1024x767.webp","categories":["Adventure"],"description":"test","isFeaturedPost":true}`

### Expected Behavior

Here is the issue 

1. A **error toast** should not give the **error code** it should give the **error message** why the error has occurred "`Image URL must end with .jpg, .jpeg, or .png`" in this case 
2. if a image is not selectable it should not be there in the select images 

### Reproduction URL

https://github.com/krishnaacharyaa/wanderlust

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/add-blog'
2. Fill the form 
3. Select the specific image which ends with .webp
4. hit post blog button
```

### Screenshots

![image](https://github.com/krishnaacharyaa/wanderlust/assets/80254854/7548e352-e430-42cd-a75a-f725d8de9f8a)

### Testcase

```bash
{"title":"test","authorName":"test","imageLink":"https://i.ibb.co/KLwfZzG/Maldives-1024x767.webp","categories":["Adventure"],"description":"test","isFeaturedPost":true}
```

### Browsers

Chrome

### OS

Windows

**Comment by geetanjalichawla** [comment]
@krishnaacharyaa i want to claim this issue. when ever it get confirmed

**Comment by geetanjalichawla** [comment]
@krishnaacharyaa is that looks better now 
also can i claim this issue ?

**Comment by geetanjalichawla** [comment]
Stage1 : fixing webp issue 
we to do that we can either fix the title from the `Blog cover image (jpg/png/webp)`  to ` Blog cover image ( .jpg, .jpeg, or .png)`
or we can add .webp in backend and fix the error message from `.jpg, .jpeg, or .png` to `.jpg, .jpeg, or .webp`
@krishnaacharyaa  suggest me what should i do 

Stage2: fixing the error code to error message as i can see in the toast we are seeing error as `Error: Request failed with status code` to the right error message we we get from backend 

Enhancement : i am not sure should we add that in a separate issue or do it here but the `form validation` such as we should have minimum 3 length of blog title 20 characters of  blog connect etc

**Comment by krishnaacharyaa** [comment]
> we can add .webp in backend and fix the error message from .jpg, .jpeg, or .png to .jpg, .jpeg, or .webp

Yes, we need to make sure we take in webp type of images without giving any error, it should be a simple fix, you have to even change in the test cases to include this properly.

Acceptance criteria for this is, all the test cases should run perfectly fine 

> fixing the error code to error message as i can see in the toast we are seeing error as Error: Request failed with status code to the right error message we we get from backend

That's a good catch, can we create new enhancement ticket for this. And work there, helps in better seperation of concerns
