### ISSUE TITLE
Opening post with link doesn't work

### ISSUE THREAD

**Issue by kuldeepjambhulkar** [krishnaacharyaa/wanderlust#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we open a post by link, we get 404

### Expected Behavior

Correct post according to the link should open

### Reproduction URL

https://wanderlust-beta.vercel.app/details-page/a-journey-through-the-marvelous-beaches-of-maldives-and-a-marvelous-experience/653441167c11e03b70e9161b

### Reproduction steps

```bash
1. Open a blog post
2. Copy the URL
3. Paste the URL in new tab
```

### Browsers

Chrome

### OS

Windows

**Comment by assudani66** [comment]
This is happening because in Frontend 
There is no Vercel.json file and thats why its not getting configured for child links 
Solution:
We need to create a Vercel.json File in the Frontend folder and paste the following code in it 
and it will start working 
```
{
  "rewrites": [{ "source": "/(.*)", "destination": "/" }]
}

```
If you want to why its happening this Article explains it 

https://dev.to/david_bilsonn/how-to-fix-vercel-404-error-child-url-path-issues-n0o

**Comment by krishnaacharyaa** [comment]
@assudani66 yes, we need to set this in vercel.json as you have commented above,. Thank you for your comment, would you wish to contribute in this issue? 
I'll assign it to you, if you are comfortable

**Comment by assudani66** [comment]
Yes sure I can take that up

**Comment by krishnaacharyaa** [comment]
Can we get some updates on this @assudani66

**Comment by krishnaacharyaa** [comment]
@assudani66 can we kindly get updates on this

**Comment by krishnaacharyaa** [comment]
@assudani66 are you working on this issue, Else we will re-assign this to some other potential candidate

**Comment by kami-codes** [comment]
Hey! You can assign me. I will try my best to do it.

**Comment by assudani66** [comment]
Hey @kami-codes 
the I had added the answer earlier you can follow along with it 
https://github.com/krishnaacharyaa/wanderlust/issues/79#issuecomment-1855318003

**Comment by assudani66** [comment]
> @assudani66 are you working on this issue, Else we will re-assign this to some other potential candidate

Ya please go ahead 
Will take up any other tasks

**Comment by krishnaacharyaa** [comment]
@assudani66 can you take up the Auth UI? with react-hook-form
