### ISSUE TITLE
UI - small button on the latest post card redirecting back to normal tab

### ISSUE THREAD

**Issue by mohamedshamil7** [krishnaacharyaa/wanderlust#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when clicking on that button , it redirects back to a normal tab
[screen-capture.webm](https://github.com/krishnaacharyaa/wanderlust/assets/116346644/80c727cd-bf31-4d91-9932-4c1b9b4ad870)

### Expected Behavior

it should open the specific blog or it should open the specific  blog in a new tab

### Reproduction URL

https://github.com/mohamedshamil7/wanderlust

### Reproduction steps

```bash
1. Go to https://wanderlust-beta.vercel.app
2. Click on  the small button on the top right corner of the latest post card
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome, Safari

### OS

Mac

**Comment by krishnaacharyaa** [comment]
@mohamedshamil7 video isn't accessible, kindly let me know what's the issue in the Discord with illustration
