### ISSUE TITLE
[BUG] Issue with the title alignment

### ISSUE THREAD

**Issue by anishsoni29** [krishnaacharyaa/wanderlust#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "All Posts" title is not aligned with the image.

### Expected Behavior

All Posts should be aligned with the image box below.

### Reproduction URL

https://wanderlust-beta.vercel.app

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app'
2. Scroll down to 'All Posts'
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
https://cdn.discordapp.com/attachments/1184178942459007136/1184902389359181904/image.png?ex=658da958&is=657b3458&hm=7110333f0ac297f5689172ad502f5bf267f36af41aeea68be52c63f1dff2376f&
```

**Comment by Deblin798** [comment]
Hi I would like to take up this issue

**Comment by Deblin798** [comment]
Hi @anishsoni29 could you please confirm whether this is the bug that you referred to?
![image](https://github.com/krishnaacharyaa/wanderlust/assets/62069462/ced00168-c1cc-4f0c-91f5-ca7b897e2152)
