### ISSUE TITLE
[ENHANCEMENT] Refactor the hardcoded string values and http status code in the backend

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#90]
### Description

To refactor the hardcoded string values and https status codes in the controllers and test cases in the backend
<img width="867" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/61256dce-624b-440e-8cc4-342799fcd398">

### Current Behavior

Currently we are hardcoding values like 400, 500, 200 and even the response messages are hardcoded in the `post-controller` and we are using the same hardcoded values in the testcases aswell. We need to refactor this.

### Proposed Enhancement

All the strings should be put in a constants file and http status code should be taken from https://www.npmjs.com/package/http-status-codes, 

### Use Case

Single source of truth and will reduce the margin of errors

**Comment by Imrankhankhattar** [comment]
Can you please assign it to me.

**Comment by krishnaacharyaa** [comment]
@Imrankhankhattar Please let us know your approach in brief and estimation to complete

**Comment by Imrankhankhattar** [comment]
@krishnaacharyaa Considering the implementation, it seems unnecessary to rely on an external library for HTTP statuses. 
We can create dedicated constant files to manage status codes and messages. This approach ensures that we have control over the specific messages and avoids unnecessary dependencies on external libraries.
Time estimation : 2-3 hrs

**Comment by krishnaacharyaa** [comment]
@Imrankhankhattar, that seems like an interesting bold claim. I'm up for it.
Kindly make sure that the names are following the standards such as INTERNAL_SERVER_ERROR, OK and the like...

p.s: follow the guidelines and issue description :)
