### ISSUE TITLE
[ENHANCEMENT] Updating the Latest Post section

### ISSUE THREAD

**Issue by Raghunandan-29** [krishnaacharyaa/wanderlust#91]
### Description

Whats'new --> Latest Posts Sections should show the latest post by date

### Current Behavior

When I added new blog it is shown in Latest Posts section, but there are other blogs latest by date than the one appearing in this section

### Proposed Enhancement

To make the Latest Posts Section should render the blog post by filtering with dates

### Use Case

NA

### Blockers

NA

### Additional Information/ Attachments

Is there any better way to resolve this Issue ?

**Comment by krishnaacharyaa** [comment]
@Raghunandan-29, Can you kindly close this and raise it as a bug, and provide images as proof because we already handle this below case
> To make the Latest Posts Section should render the blog post by filtering with dates

Open to any corner cases if missed.
