### ISSUE TITLE
[BUG] In All Post section Card

### ISSUE THREAD

**Issue by Raghunandan-29** [krishnaacharyaa/wanderlust#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the card which has large description is clicked, some part of the description is in viewport initially not the top of the post, that is Image and the start of description is not in viewport initially when the card is clicked.
Current behaviour :

<img width="1440" alt="Screenshot 2024-01-05 at 11 18 22 PM" src="https://github.com/krishnaacharyaa/wanderlust/assets/102844162/90c256c4-79d9-46cc-bee5-355a8baaba46">

### Expected Behavior

When is card with large description is clicked , the top of post ( that is image and the start of the description )should be in viewport initially.
Expected behaviour :

<img width="1439" alt="Screenshot 2024-01-05 at 11 18 36 PM" src="https://github.com/krishnaacharyaa/wanderlust/assets/102844162/ef94d11f-48a1-496c-8fce-08ab8896fb4c">

### Reproduction URL

https://github.com/Raghunandan-29

### Reproduction steps

```bash
1. Go to 'All Post section'
2. Click on 'Capturing the Cityscape at Night: A Mesmerising Experience by Alice Smith' card
3. Checkout the content which in viewport initially.
4. Initially the top of this post page should be in viewport rather than the part of description.
5. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by krishnaacharyaa** [comment]
That's a very precise observation, thank you for the bug @Raghunandan-29, 
https://stackoverflow.com/a/61602724/13431819 this should ideally solve the problem for anyone who wants to solve this :)

**Comment by Raghunandan-29** [comment]
I resolved this issue and will raise the PR
