### ISSUE TITLE
[BUG] In Theme-Toggle-Button

### ISSUE THREAD

**Issue by Raghunandan-29** [krishnaacharyaa/wanderlust#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When theme is toggled to dark and if the page gets refresh/reload, theme-toggle-button initially renders light theme for a fraction of seconds and then toggled to dark theme.
current behaviour:

https://github.com/krishnaacharyaa/wanderlust/assets/102844162/60e9f12e-2df5-4a9b-a58c-e77b5570b3c6

### Expected Behavior

When theme is dark, then theme-toggle-button should render dark theme initially if the page gets refresh/reload.

### Reproduction URL

https://github.com/Raghunandan-29

### Reproduction steps

```bash
1. Go to 'homepage'
2. Toggle theme to 'dark'
3. Refresh the 'homepage'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by krishnaacharyaa** [comment]
@Raghunandan-29 interested in picking this up?

**Comment by Raghunandan-29** [comment]
Yes, I am

**Comment by Janith-Chamikara** [comment]
Hey is this issue still remains
